### ISSUE TITLE
Бутылки от зелий (Сталкерские привычки...)

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#100]
_Вынесено из #21 (Сталкерские привычки...)_

Когда выпиваем зелье, должен оставаться пустая бутылка.

----
@albel4 commented on Oct 13
По идее бутылки от зелий должны быть одноразовыми. Как шприцы. Зелья при смешивании ведут себя не предсказуемо.

**Comment by Mikola314** [comment]
"По идее бутылки от зелий должны быть одноразовыми. Как шприцы." 
"Засрём Средиземье использованными шприцами!" ?(
Шприцы бывают стеклянные и в некоторых сферах используются до полного разрушения.
Это сейчас производство стеклянных изделий налажено на станках, а раньше все бутыли приходилось выдувать самому.

Предлагаемые варианты решения:
1) игрок получает просто пустую бутылку и сразу может использовать для нового рецепта
2) делаем рецепты по отмывке бутылок и тарелок, для повторного применения
