### ISSUE TITLE
Не работает картограф. Прикрутить новый.

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#101]
С некоторых пор картограф не работает.

Из-за скорости старого и ряда других проблем, решили прикрутить новый, предложенный @googolgl .
см. коммент

**Comment by Mikola314** [comment]
Elrick предлагает попробовать этот мапер:
https://github.com/thomasrudin-mt/minetest-tile-server

**Comment by alek13** [comment]
А починить существующий не проще ?

**Comment by alek13** [comment]
@albel4 протестил. Напоролись на 
```
java.lang.IllegalArgumentException: block version not supported: 25
```
проверка поддержки версии и выброс исключения здесь:
https://github.com/thomasrudin-mt/minetest-tile-server/blob/master/src/main/java/io/rudin/minetest/tileserver/util/MapBlockParser.java#L57

у них есть таск по этому поводу, откомментил в него: https://github.com/thomasrudin-mt/minetest-tile-server/issues/7#issuecomment-445548529

**Comment by vladtcvs** [comment]
> С некоторых пор картограф не работает.

С довольно давних, надо сказать

**Comment by alek13** [comment]
наш PR с поддержкой нужной версии был принят: https://github.com/thomasrudin-mt/minetest-tile-server/commit/f689bafd31cb03ce58d1a4f666b3db06612632a9
можно юзать.

**Comment by kevicky9** [comment]
https://github.com/minetest-mapserver/mapserver

**Comment by alek13** [comment]
Не актуально, пилим panorama. Уже введена в эксплуатацию MVP (http://map.lord-server.ru/)
