### ISSUE TITLE
Нет цены на товар у торговцев

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#104]
У торговцев (мобов) не у всего товара есть цена.
Точно нет цены на:
 - Галворновый меч
 - Стальной меч
 - Серебряный меч
 - Мифриловый кинжал
 - Серебряный боевой топор

**Comment by googolgl** [comment]
Исправил https://github.com/lord-server/lord/commit/ea3ed58706ba568b662e07df7db0e685b0454145
Нельзя указывать алиасы в списке товаров.

**Comment by alek13** [comment]
протестированно
