### ISSUE TITLE
Стандартный механизм приватинга для рамок

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#1050]
**Проблема:**

При совместной игре, когда есть общая база/дом, рамки очень часто используются для пометки сундуков -- визуальной наглядности содержимого сундука.
Однако переставить/убрать рамку или втавить новый предмет в неё может только тот, кто поставил её изначально.

Было бы удобнее, если рамку переставить мог и твой "сосед"/друг.

**Предложение:**

Сделать расчёт приватности рамки на основе стандартного механизма приватов и areas.

**Дополнительная информация:**

Открытым остаётся вопрос: что делать с теми рамками, которые уже установлены

**Comment by VanicGame** [comment]
Можно сделать рамки на приватах и areas и личные рамки
