### ISSUE TITLE
Неизвестный итем, полученный из мордоского песка в дробилке

### ISSUE THREAD

**Issue by VanicGame** [lord-server/lord#1052]
Связано с #1002 
![screenshot_20230605_173235](https://github.com/lord-server/lord/assets/82447582/d799f3d1-bbe3-4b78-b176-2124d06d4475)

**Comment by alek13** [comment]
на тестовом норм
![image](https://github.com/lord-server/lord/assets/1972329/be76eaad-b2eb-4e65-8031-0cc8d8d72d7e)
