### ISSUE TITLE
Не работает кольцо воды на полигоне

### ISSUE THREAD

**Issue by Petus228666** [lord-server/lord#1054]
Не работает кольцо воды на полигоне 

Как воспроизвести: 
1- надеваем кольцо воды
2- ищем ~~злюку~~ агрессивного моба
3- ~~злюка~~ агрессивный моб атакует
4- видим, что кольцо нас не защищает от ~~злюки~~ моба
5- умираем

 - OS: [<Windows 11>]
 - Client version: [5.5.0]
 - Device: [ПК]

У меня то же самое. Vanic.

**Comment by alek13** [comment]
После фикса урон не проходит, однако на HUD отображается не верно.
Вынесу в отдельную такску, т.к.
 - это уже не `CRITICAL`
 - HUD требуется переписать
