### ISSUE TITLE
Не надевается грязная одежда

### ISSUE THREAD

**Issue by vladtcvs** [lord-server/lord#1093]
**Описание ошибки:**

Невозможно надеть на себя Dirty Trousers и Dirty Jacket
![screenshot_20230804_002647](https://github.com/lord-server/lord/assets/3390973/e94c05e2-7505-4667-8a4a-ea6e2eb0393c)

**Как воспроизвести:**

Шаги воспроизведения на сервере
1. Открываем инвентарь
2. Берём Dirty Jacket
3. Устанавливаем на слот рубашки
4. Он не устанавливается

**Ожидаемое поведение:**

Dirty Jacket в слоте рубашки

с Dirty Trousers аналогично

**Информация о клиенте:**

 - OS: Linux
 - Client version: 5.6.1
 - Device: ПК

**Comment by vladtcvs** [comment]
Уточнение:

Грязную одежду можно постирать.

Предложение:

добавить возможность надевать грязную одежду, но чтобы это приводило к минусам для игры

**Comment by alek13** [comment]
На данный момент не является багом, а предложение слишком размыто,
поэтому закрываю.

Можно обсудить отдельно в Дискорде и открыть новый таск,
но с учётом текущего roadmap, доберёмся не скоро.

Даже если взять как параллельно разрабатываемую фичу,
её проработка и чёткая постановка приведут к тому,
что нужно сначала закончить рефакторинг, который у нас в roadmap.

Если есть желание, давай обсудим, поймём что хотим, набросаем что для этого нужно сделать.
В отдельный Эпик выкенем и запилишь.
