### ISSUE TITLE
 Каменные блоки: Пустынный гравий: добавить в генерацию

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#1098]

**Comment by vladtcvs** [comment]
Где должен генериться пустынный гравий?

**Comment by alek13** [comment]
в биомах с пустынным каммнем.
```lua
biome == BIOME_DUNLANDS or biome == BIOME_ROHAN
```

**Comment by vladtcvs** [comment]
Как он должен генериться, в виде случайных вкраплений в пустынный камень или как-то еще?

**Comment by alek13** [comment]
как угодно. Стандартным способом вряд ли получится, а `lottmapgen` -- тот ещё гемор (сейчас, конечно стало чуть полегче в восприятии, но всё же), так что как получится :)

**Comment by vladtcvs** [comment]
У нас генерация биомов происходит весьма своеобразным способом. После того, как основной мапген уже прошел, мы составляем карту влажности, температуры, итд, по ним определяем текущий биом и если биом рохан или дунланд, то заменяем камень и руды на пустынный камень.

Выводы: 
1) делать генерацию пустынного гравия как руды смысла нет
2) его надо генерить вручную там же, где заменяется камень на пустынный камень
