### ISSUE TITLE
Приписка "\u0001\u0002\u0003" к предметам

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#111]
Разобраться с проблемой появления приписки "\u0001\u0002\u0003"  к предметам. Появилось после перехода на 0.4.16.
Примеры:
Item lord_money:silver_coin 18 6 "\u0001\u0002\u0003"
Item lord_money:silver_coin 25
Item screwdriver:screwdriver_galvorn 1 13792 "\u0001\u0002\u0003"
Item lottblocks:palantir_guide 1 0 "\u0001\u0002return {[\"page\"] = 5}\u0003" где {[\"page\"] = 5} выбранная последний раз страница

**Comment by googolgl** [comment]
Эту проблему я помню.
Эти приписки появлялись если предметы забирались у трейдеров.
Но вроде ее исправляли ?

**Comment by Mikola314** [comment]
googolgl, кто бы и когда исправлял?

**Comment by googolgl** [comment]
Когда крайний раз наблюдался этот баг?
И как его воспроизвести?

**Comment by alek13** [comment]
баг в самом Minetest: minetest/minetest#6057
PR с багфиком замерджен, но таск не закрыт ещё.
После обновления на новую версию, проверяем, закрываем.
