### ISSUE TITLE
Неудовлетворительно низкая производительность WorldEdit move

### ISSUE THREAD

**Issue by vladtcvs** [lord-server/lord#1118]
**Описание ошибки:**

При перемещении даже небольшого здания (область объемом 40-50 тысяч нод) с помощью WE перенос длится долго - от 30 до 60 секунд, и возможен краш сервера. При более крупных областях все еще хуже.

**Comment by alek13** [comment]
обновить нужно WE, они это исправили.
https://github.com/orgs/lord-server/projects/6/views/3
#783

**Comment by alek13** [comment]
мод обновлён, приедет в след. релизе
