### ISSUE TITLE
Повысить сытность от салатов, супов и хлеба.

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#114]
Томатный суп делается из Жареных томатов - нужно увеличивать сытность.
Подправить текстурку крекера на несколько крекеров и поменять перевод на "Крекеры" или поменять кол-во при крафте и значение сытости.

**Comment by vladtcvs** [comment]
Кстати, а почему жареные томаты более сытные, чем свежие?

**Comment by Mikola314** [comment]
Решено оставить "Крекер" в единственном числе и будущем поменять кол-во при крафте и значение сытости. В https://github.com/lord-server/lord/pull/147 текстуру оставили старую с добавлением детализации.

**Comment by alek13** [comment]
Done.
- [project](https://github.com/orgs/lord-server/projects/26/views/1)
- [analytics](https://github.com/lord-server/lord/issues/1501)
