### ISSUE TITLE
нельзя купить парусную лодку у торговца

### ISSUE THREAD

**Issue by Petus228666** [lord-server/lord#1175]
нельзя купить предмет
![изображение](https://github.com/lord-server/lord/assets/122599616/545eeaac-3dfd-403f-bb7a-fe19fe66283e)

**Как воспроизвести:**

Шаги воспроизведения
1. ищем челнока людской рассы
3. просим к покупке  парусную лодку
2. глупый торговец не знает цены на свой же товар
4. видим ошибку
 - OS: [Windows 11]
 - Client version: [<5.7.0>]
 - Device: [ПК]

**Comment by alek13** [comment]
Лодка является алиасом:
```
ERROR[Server]: Can't add item to Trader inventory: undefined item `boats:sail_boat` or its an alias.
```
нашлось вроде только у человека, нужно потесить.

**Comment by Petus228666** [comment]
Тесты показали что баг исправлен
