### ISSUE TITLE
Remove `Core/builtin/locale/__builtin.ru.tr` translations after it apears in MT

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#1187]
- create PR in MT (see MT[`builtin/locale`](https://github.com/minetest/minetest/tree/master/builtin/locale))
 - remove after:
   - merged & released https://github.com/minetest/minetest/pull/13896
   - our server upgraded to that new version

**Comment by Doloment** [comment]
Замержено в октябре 2023, вышло в 5.8, @alek13
