### ISSUE TITLE
Слетают эффекты от зелий при получении урона

### ISSUE THREAD

**Issue by filkar2005** [lord-server/lord#1217]
При получении урона слетает эффект скорости от зелья, также работает с зельем для высоких прыжков (с остальными просто не проверял)
После того, как слетает эффект скорости от зелья, достаточно выпить зелье для высоких прыжков (с другим не проверял), и тогда скорость возвращается  (до получения следующего урона).
Также после того, как действие зелья закончилось, скорость падает сильнее, чем должна - сняв мифриловые ботинки, я стал идти быстрее, чем с ними.

**Comment by alek13** [comment]
@Petus228666 , проверьте, плиз, баг.
Опишите чуть подробнее шаги воспроизведения.
(после проверки, поставьте метку `confirmed` вместо `unconfirmed`)

**Comment by Petus228666** [comment]
1-берем зелье:напиток энтов
2- пьем
3- получаем бафф
4-получаем урон(я получал от падение,но думаю не важно)
5-бафф уходит раньше времени,но иконка с бутылкой(та,что свидетельствует о том,что было использовано зелье) остается

**Comment by alek13** [comment]
@Petus228666 , закрывай, если теперь не воспроизводится

**Comment by alek13** [comment]
по информации от @Petus228666 , больше не воспроизводится после перехода на новую систему эффектов и физики.
