### ISSUE TITLE
Броня из мифрила сильнее кольца воды

### ISSUE THREAD

**Issue by Petus228666** [lord-server/lord#1231]
**Описание ошибки:**

Нельзя пробить броню из мифрила. Проверенно: болтами из мифрила,топоры гномов

**Как воспроизвести:**

Шаги воспроизведения на [полигоне]:
_(для наглядности можно зайти на арену из зелёного мрамора)_
_Прим.: нужны 2 игрока._
1. Для первого игрока:
  1.a Достаем (команда `/list`) набор брони (поиск: `lottarmor:.*mithril`)
  1.b Открываем инвентарь, ставим сет в слоты брони
2. Для второго игрока:
  2.a Достаем (`/list`) "Гномий метательные топоры" (`arrows:axe_dwarf`)
  2.b "Стреляем" в первого игрока
3. Здоровье не уменьщается

То же поведение для "Мифриловый арбалет" (`lottthrowing:crossbow_mithril`) с миф. болтами (`arrows:bolt_mithril`)
 
**Ожидаемое поведение:**
Пробой брони: здоровье уменьшается

**Информация о клиенте:**

 - OS: [<|Windows11>]
 - Client version: [<5.7.0>]
 - Device: [ПК]
 - В кольце воды урон проходит по игроку

**Comment by Doloment** [comment]
Не актуально после  2024.07.II
