### ISSUE TITLE
Неочевидность структуры кодовой базы

### ISSUE THREAD

**Issue by Doloment** [lord-server/lord#1235]
@alek13 Мы с Ваником уже горели с этого, и еще погорим.

Вот объясните мне, почему Player хранит в себе такие моды как `equipment_clothing`, `equipment_armor`, `equipment`, `appearance`, но ни в одном из них нет ни регистрации одежды, ни регистрации брони?
Если эта папка подразумевает что в ней только API для игрока не логичнее ли было бы её (и вообще максимально все API), раз уж они и так отделены от регистраций, а также текстур и других медиа, поместить в `Core`, или хотя бы изолировать от остального контента?

Далее, папка `Tools`.
Помимо инструментов/брони содержит предметы одежды, стрел, монет, зелий. Вопрос: зачем папка названа вводящим в заблуждение определением, когда там помимо инструментов очень много простых предметов? Предметы (не путать с крафтайтемами) и так включает в себя инструменты.

Вот что предлагаю.

- `Tools` переименовать в `Items`
- `Player` переместить в `Core`
или, в альтернативу 2 предложению:
- `Blocks`, `Entities`, `Items`, `World` объединить в одну папку `Content` или с подобным названием

**Comment by alek13** [comment]
@Doloment , ну если хочешь пообсуждать у кого с чего "горит", то давай.
У меня, например, горит с того, что вы с Ваником то приходите на проект (и даже помогаете, за что спасибо), то опять с него уходите (можно сказать, хлопнув дверью), и так постоянно. И после этого спустя почти год вдруг появляетесь и говорите, что вам тут что-то не нравится.
Это как минимум странно.

Ну а если серьёзно, то давай вспомним как это было.
Когда я предложил всем накидать хоть какой-то свой вариант и предложить структуру, все почему-то технично промолчали. Один раз выдернул тебя, что-то мы обсудили совсем немного, ни к чему конкретному не пришли и ты ты убежал.

После чего я организовывал структуру один так, как я это вижу. Да и к тому же, если ты помнишь, эта структура была изначально сделана как "первый промежуточный вариант", т.к. сразу было понятно, что во многих модах свалено всё до кучи и что просто так без рефакторинга их один к одному не раскидаешь по папкам, какая бы структура ни была.

И да!, даже этот промежуточный вариант всё ещё в процессе (если посмотришь повнимательнее).

Ну и совсем по делу:
1. `Core` - в ней собраны всевозможные расширения языка (lua), хелперы, расширения API самого minetest (например, `minetest.register_on_dungeon_generated()`). Если обобщить, то всё то, что не относится именно к этому проекту и его специфике и в теории может спокойно переехать любой другой проект. (Примечание: на данный момент там есть несколько модов, которые там находятся спорно или временно).
Тут бесспорно `equipment_clothing`, `equipment_armor`, `equipment` -- претенденты на переезд в `Core`, однако, не каждому проекту требуются такие моды и стоит ли их туда переносить -- большой вопрос. Можно было бы перенести в `Game`, но всё же это экипировка именно игрока (не мобов, ни ещё кого-то). Ну и когда смотришь на папку `.../Player/equipment/`, она наглядно говорит о том, что это экипировка игрока. Поэтому эти папки пока что в `Player`, но всё обсуждаемо. Другой вопрос, что вы вроде как с проекта ушли ;)
ps: `Player/appearance` -- внешний вид **_игрока_** и там далёеко не API, там вообще пока что старый неотрефаченный легаси код, который никокого отношения к Core не имеет.
2. **_`Tools` переименовать в `Items`_**
Вот тут тоже вроде да, но ... есть ньюансы. Слово Tools имеет достаточно широкое значение и подходит больше к тому, что сейчас в этой папке. Слово Items тоже подходит, но в контексте minetest'а имеет определённое значение, при этом minetest-item'ы раскиданы по всему проекту: и в `Blocks`, и в ..., ... . Отделять их тащить все в эту новую папку `Items` нет никакого смысла, как ты понимаешь. Ну например, нет смыссла перетаскивать итем, с помощью которого в улей к пчёлам залазят. Он вполне логично и правильно лежит в моде с ульями. А раз item'ы раскиданы по всему проекту, а не только в этой папке, назвав её так, можно ввести в заблуждене. Но всё же и `Tools` звучит так себе, особенно, если учесть, что внутри есть мод `tools`. В итоге `Tools/tools` -- масло масленное. Если подберётся какое-то другое слово, может будет лучше. Ещё есть есть мысль разделить `Tools/tools` на оружие (weapons) и орудия труда (лопаты, кирки,...), но орудия труда -- это опять таки tools ))). Если слово не подберётся, и не получится как-то нормально разделить `Tools/tools`, то тут пожалуй переименовать в `Items` -- это наименьшее из бед, и стоит будет так и сделать. Но опять таки: вы вроде ушли с проекта ;)
3. **_`Player` переместить в `Core`_**
Тут я вот совсем не согласен. Player никак не относится к Core (с учётом описания выше что такое Core). Я не исключаю, что у тебя есть некое своё видение, в котором папка Core играет немного другую роль и в твой концепт этот перенос логичнее укладывается, но напомню "когда я спрашивал, все технично промолчали" ;)
4. **_`Blocks`, `Entities`, `Items`, `World` объединить в одну папку `Content` или с подобным названием_**
ммм... И на этом уровне останется `Content` и `Core`? и появится доп. вложенность? А смысл ?  Если только подчеркнуть текущее значение `Core` (то, что там всё, что не относится к конкретно этому проекту) ? Что-то в этом есть... Хм, в ответ родилась другая мысль: вынести `Core` на папку выше, т.к. по идее она не относится к `lord` (если не считать тех модов, которые там пока что временно и стрктура в процессе формирования).

----
P.S.: в общем, текущая версия ооочень примерная и в процесе, всё обсуждаемо, если ты (или вы) всё-таки принимаете участие не на месяцок. (Ну сам понимаешь: нет особо желания расписывать и обсуждать, если ты через условных пару недель всё-равно опять пропадёшь).

P.P.S.: дальнейшее обсуждение думаю стоит продолжить в Дискорде в канале `#код` в отдельной ветке, как мы обычно и делали, а на GitHub уже гтовые договорённости зафиксировать в виде задач.
Можно, кстати, попробовать обсуждения вести в GitHub'овских Discussions ([вот пример как это выглядит](https://github.com/github/gh-gei/discussions)). Возможно будет удобнее, чем в Дискорд'е. Но пока что особо нет смысла, даже если ты возвращаешься и не на месяц-два. Хотя ради интересна можно и вдвоём попробовать.
