### ISSUE TITLE
У картин сломана палитра цветов

### ISSUE THREAD

**Issue by VanicGame** [lord-server/lord#1302]
**Описание ошибки:**

Картины на сервере отображаются некорректно: цветовая палитра не соответствует ожидаемой. Старые картины изменили свою палитру.

----
EDIT:
**Дополнительная инфа:**
 - произошло после перехода сервера на `5.8.0`
 - ребята с "Наши ТуТ" сказали, что они обновили на вот эту версию: https://github.com/sfence/painting и у них всё ок. Однако, они не припомнили при каких обстоятельствах это было (до/после обновления сервера). Но попробовать стоит

**Comment by alek13** [comment]
Пример:
было:
![image](https://github.com/lord-server/lord/assets/1972329/e9d7e79c-8591-4d6e-8496-cb4bcdc86e5d)
стало:
![image](https://github.com/lord-server/lord/assets/1972329/fbf03967-4ffc-4178-84b6-8ad8f9063bfc)

**Comment by alek13** [comment]
Для воспроизведения локально, прикрепляю сохранённую картину:
[Dormi-art-ladybug.mts.gz](https://github.com/lord-server/lord/files/15139573/Dormi-art-ladybug.mts.gz)
[Dormi-art-ladybug.meta.gz](https://github.com/lord-server/lord/files/15139574/Dormi-art-ladybug.meta.gz)

 - распаковать
 - положить в папку `schems` мира (напр., `~/.minetest/worlds/lord/schems`)
 - зайти в игру с этим миром
 - поставить WE-pos1: `//1`
 - загрузить картину: `/L Dormi-art-ladybug`
