### ISSUE TITLE
Floating plums bug

### ISSUE THREAD

**Issue by Kommissar7** [lord-server/lord#1359]
**Описание ошибки:**
После релиза 2024.4 обнаружился небольшой баг: Сливы не падают с выращенных деревьев, а остаются парить в воздухе. При этом, раньше этого бага не было.

*Не получилось прикрепить изображение*

**Как воспроизвести:**

1 - Берём саженец сливы (default:plum_sapling)
2 - Сажаем его в землю (default:dirt_block)
3 - Ждём пока слива вырастет
4 - Срубаем сливу
5 - Любуемся парящими в небе сливами

Где проверено: Равнины близ базы Масонов на сервере LORD.

**Ожидаемое поведение:**

После срубания сливы её плоды должны падать на землю

**Дополнительная информация:**

×

**Comment by Doloment** [comment]
Дубликат #1330, хотя и хорошо описанный, но в первом посте есть скриншот
