### ISSUE TITLE
Невидимые рыбы

### ISSUE THREAD

**Issue by vladtcvs** [lord-server/lord#1366]
**Описание ошибки:**

Рыбы под водой не видны если смотреть сверху

Рыбы видны в 2 случаях:
1) торчат над водой
2) игрок сам находится по водой

Рыбы, находящиеся в воде полностью, для игрока сверху невидимы
![image](https://github.com/lord-server/lord/assets/3390973/07e032f0-048a-4141-b2d6-c1a9befd0bd2)

Minetest 5.6.1, linux, radeon 6600

**Comment by vladtcvs** [comment]
Дополнение: когда находишься под водой, то рыбы над водой не видны

**Comment by alek13** [comment]
FYI: на 5.8.0 та же проблема

**Comment by vladtcvs** [comment]
при этом игрок стоящий по пояс в воде, виден целиком

**Comment by vladtcvs** [comment]
проблема касается любых entity, поверхность воды скрывает все части entity, которые за ней, независимо от того с какой стороны смотришь

**Comment by vladtcvs** [comment]
проблема не распространяется на лошадей и npc
