### ISSUE TITLE
Плащ клана

### ISSUE THREAD

**Issue by Kommissar7** [lord-server/lord#1378]
![20240525_210502](https://github.com/lord-server/lord/assets/170120326/7b0137c8-6678-4005-be46-b1f91770059b)
![eb6388a72eca33a9](https://github.com/lord-server/lord/assets/170120326/fa609f16-a0c5-4698-92fe-6c52a56bcdcb)

Хотелось бы добавить плащи для Интерна. Выше прикрепил обе текстуры (как отображается на игроке и как отображается в инвентаре.).

**Comment by alek13** [comment]
@Kommissar7 , тут с тестурами беда

**Comment by Petus228666** [comment]
![cc56ca3cc23ed424](https://github.com/user-attachments/assets/fca43cf1-262a-4220-8a45-85207c914bc9)
![eb6388a72eca33a9](https://github.com/user-attachments/assets/cb50861d-6dee-4c77-85b9-624e1d905cea)
 забирайте
