### ISSUE TITLE
Доски из lord_planks нельзя сломать рукой

### ISSUE THREAD

**Issue by ssdaniel24** [lord-server/lord#1379]
**Описание ошибки:**

Невозможно сломать рукой любые доски из `lord_planks`.

![image](https://github.com/lord-server/lord/assets/107036969/47cd471e-486e-4391-ba07-d744c5d8a478)

**Как воспроизвести:**

Шаги воспроизведения на локальном окружении:
* взять любые `lord_planks:*` из `/list`
* попробовать сломать рукой

**Ожидаемое поведение:**

Доски lord_planks могут ломаться рукой точно так же как и `default:wood` (Яблоня).

**Comment by Kommissar7** [comment]
The actual issue is that apple logs can be broken by hand while other logs and planks can't. We should make all of them breakable only if you are using an axe.

**Comment by Kommissar7** [comment]
So, i can break tree trunk by arm, but can't do this with the tree planks? I don't think it's logical.

You shouldn't be able to break any trunk or planks without an axe, this is what I was saying.

**Comment by Doloment** [comment]
> but what should player do if he will arrive in a biome without default wood?
find a biome with default wood :D

**Comment by alek13** [comment]
@ssdaniel24 
- if its just local(other) copy of game -- see Doloment answer
- if its our server -- on each spawn we gives you the opportunity to get sticks
