### ISSUE TITLE
Балрог-слабак

### ISSUE THREAD

**Issue by albel4** [lord-server/lord#14]
- [x] Балрог малоподвижен (не может запрыгнуть на блок). Аналогичная проблема у Варгов. Дело в том, что модельки у них развернуты на 180 градусов и в mobs.api.lua где-то неправильно вычисляется вектор скорости. Если модельки не разворачивать (rotate=0) они начинают пятится и перепрыгивают препятствия. При walk_chance = 0 отключается анимация движения но зато преодолеваются препятствия (независимо от rotate).
- [ ] Маленький радиус поражения. 
- [x] Желательно ему передать фаер-болы, а назгулам “дать” мечи прокачать на пробитие брони от колечка(если получится).

**Comment by narrnika** [comment]
Попался под руку вот этот мод: https://forum.minetest.net/viewtopic.php?f=11&t=11813
Я не предлагаю его ставить, я лишь хочу обратить внимание того, кто будет заниматься мобами, что на сопутствующем видео с youtube многие монстры бьют довольно далеко, а в файлах с их описанием в функции _register_mob_ присутствует параметр _reach_, который (по крайней мере с моим гугловским английским) можно расшифровать как радиус действия...

**Comment by Mikola314** [comment]
> Балрог малоподвижен
исправлено 
https://github.com/lord-server/lord/commit/34cd7ed42fab80d189009fe2d71c4708513acd90

**Comment by alek13** [comment]
не актуально, отложено до формирования проекта по перебалансировке мобов

**Comment by ssdaniel24** [comment]
https://content.minetest.net/packages/rheo/mobs_balrog/
