### ISSUE TITLE
Конфликт изменения ника игрока в show_health и clans

### ISSUE THREAD

**Issue by ssdaniel24** [lord-server/lord#1407]
**Описание ошибки:**

Потенциальный конфликт изменения отображающегося ника игрока в модах `lord/Player/show_health` и `lord/Player/clans`.

**Как воспроизвести:**

При входе игрока, состоящего в каком-либо клане, на арену к его нику добавляется количество его здоровья с сердечком. Если в тот момент, когда игрок всё ещё на арене, его уберут из клана, то его ник полностью сбросится.

**Ожидаемое поведение:**

Ник игрока не сбросится полностью, а оставит количество здоровья.

**Дополнительная информация:**

Как один из путей решения вижу создание мода, который предоставляет единое API для изменения ника игрока.

**Comment by alek13** [comment]
осталось применить сегменты в `show_health`: https://github.com/lord-server/lord/issues/1429
