### ISSUE TITLE
Clans v2: Автокик игроков из клана вызывает падение сервера в некоторых случаях

### ISSUE THREAD

**Issue by ssdaniel24** [lord-server/lord#1408]
**Описание ошибки:**

Сервер падает при попытке кикнуть из клана игрока, который ни разу не заходил на сервер.

**Как воспроизвести:**

* создать клан с ни разу не заходившим на сервер игроком в первые тридцать секунд после запуска сервера
* дождаться запуска автокика (30 секунд после запуска)
* увидеть падение

**Ожидаемое поведение:**

Сервер не падает, а автокик игроков игнорирует игроков, которые ни разу не заходили на сервер.

**Дополнительная информация:**

Связано с #1324.

**Comment by alek13** [comment]
> ни разу не заходившим на сервер игроком

это как ?
