### ISSUE TITLE
Clans v2: Баг: возможность добавлять несуществующих игроков в клан

### ISSUE THREAD

**Issue by ssdaniel24** [lord-server/lord#1421]
**Описание ошибки:**

В клан возможно добавить несуществующего в БД сервера игрока (т.е. игрока, который на сервер не заходил ни разу).

**Как воспроизвести:**

- Открыть любую сборку
- Зарегистрировать новый клан с несуществующим игроком или добавить несуществующего игрока в существующий клан
- Успешно

**Ожидаемое поведение:**

Команды `clans.add_player` или `clans.register` должны были выдать ошибку о том, что такого игрока не существует.

**Comment by alek13** [comment]
@ssdaniel24  есть готовая `minetest.player_exists(name)` https://api.minetest.net/minetest-namespace-reference/#misc
