### ISSUE TITLE
Не отображается текстура призрачной земли шира

### ISSUE THREAD

**Issue by Petus228666** [lord-server/lord#1428]
Описание: На сервере-полигоне LORDа по адресу game.lord-server.ru 30004 VladTs обнаружил баг:

Призрачный грунт превратился в unknown item.

Как воспроизвести:
Пока неясно
![изображение](https://github.com/lord-server/lord/assets/122599616/896b100d-5c1d-4481-a12e-803e13a252d7)

**Comment by Doloment** [comment]
Это не unknown item, это блок, у которого слетела текстура. Судя по debug-меню, это трава шира. Последним, кто делал что-то связанное с этими блоками — @alek13

**Comment by alek13** [comment]
more likely relates to https://github.com/orgs/lord-server/projects/5/views/13?pane=issue&itemId=63176620
