### ISSUE TITLE
lord_bows: выброшенный лук визуально очень большой

### ISSUE THREAD

**Issue by ssdaniel24** [lord-server/lord#1455]
**Описание ошибки:**

Новый лук из lord_bows визуально очень большой по сравнению с другими предметами.

![2024-06-12_22-51-58](https://github.com/lord-server/lord/assets/107036969/9d86687e-09ae-4b3d-8a94-f6e35ca23c0f)

**Как воспроизвести:**

1. Взять `lord_bows:bow`
2. Выбросить его
3. Удивиться размерам выброшенного предмета

**Ожидаемое поведение:**

3. Увидеть просто выброшенный предмет без особенностей.

**Comment by VanicGame** [comment]
Не баг, а фича. Размер лука был увеличен, чтобы в руке он смотрелся нормально. Тут либо-либо:
1. Либо он нормально смотрится в руке и большой в мире
2. Либо он в руке мелкий, зато нормальный в мире

Лично я предпочту первый вариант и вам советую

P.S. другие инструменты можно так же визуально увеличить в будущем

**Comment by alek13** [comment]
пожалуй.
Можно попровать найти золотую середину, если получится

**Comment by VanicGame** [comment]
Ммм, не уверен, что следует менять. Хоть лук и визуально большой, относительно блока, если отойти от привычного условного восприятия игры, то он выглядит довольно "реалистично". Проще говоря, не вижу особой проблемы в том, что он больше блока. Наоборот, это даже привлекает и выделяет его

**Comment by Kommissar7** [comment]
Так он как раз нужного размера. Раньше был слишком короткий, сейчас что надо.

**Comment by VanicGame** [comment]
Ишуе закрываю? @ssdaniel24
