### ISSUE TITLE
Перенос пустой надетой сумки в неё саму заставляет её исчезнуть

### ISSUE THREAD

**Issue by ssdaniel24** [lord-server/lord#1466]
**Описание ошибки:**

Если взять пустую надетую сумку курсором, и, не перекладывая её никуда, открыть эту же самую сумку и положить её туда, то она исчезнет вместе со своим содержимым. Совсем, навсегда.

**Как воспроизвести:**

1. Положить свою новую сумку в соответствующий слот (в данном случае "Сумка 2"). Не наполнять её, должна быть пустой.
![bag-bug1](https://github.com/lord-server/lord/assets/107036969/68469f50-f0c7-4534-b2af-d1cb9a3de863)
2. Взять курсором эту самую сумку из слота одиночным кликом, и, всё ещё "держа" в курсоре сумку нажать на кнопку этой же самой взятой сумки ("Сумка 2").
![bag-bug2](https://github.com/lord-server/lord/assets/107036969/6a6adb37-985e-4160-8709-f8e2df5342ae)
3. Положить сумку в курсоре в открывшиеся слоты (меню "Сумки 2").
![bag-bug4](https://github.com/lord-server/lord/assets/107036969/5260d5ed-616a-45d8-bf45-8ff98c3fc1ef)
4. Возвращаемся в меню "Сумки" и наблюдаем исчезновение сумки.
![bag-bug5](https://github.com/lord-server/lord/assets/107036969/cdfcc478-5a24-4ee0-91f7-0550d650c420)

**Ожидаемое поведение:**

3. Положить сумку в открывшиеся слоты не получается.
4. Придётся вернуться на меню "Сумок" и положить сумку обратно.

**Дополнительная информация:**

Игрок может получить свою сумку обратно, если сделает ещё одну и положит её в тот же слот, где была исчезнувшая сумка. Исчезнувшая сумка будет в инвентаре новой.

**Comment by alek13** [comment]
а кто у нас QA-Lead ?  я запутался... :rofl:

**Comment by Doloment** [comment]
Не могу больше воспроизвести, видимо связано с https://github.com/minetest/minetest/issues/13486, исправлено в https://github.com/minetest/minetest/pull/12595

**Comment by Doloment** [comment]
версия? 

> А я всё ещё могу!

**Comment by Doloment** [comment]
В связи с обновлением сумок требуется проверить на актуальность
