### ISSUE TITLE
PvP: Lord Bows: change LMB & RMB functionality

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#1520]
it possible fix #1519
also possible fix: "Новые луки, по-моему, с мобилы вообще не функциональные"

**blocked by:**
- #1550 
- #1551 

----
**Testing:**
- check usability on mobile
- check #1519 fixed

**Comment by Doloment** [comment]
Decided to roll with the current configuration for the convenience of using LBM for projectile pick up.
