### ISSUE TITLE
Возможность видеть остаток на складе прилавка для владельца территории

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#154]
Допустим:
 - Игрок 1: `Protector-Owner`
 - Игрок 2: `Shop-Owner`

`Protector-Owner` на некоторой территории поставил приват. Далее `Shop-Owner` договорился с ним расположить на его территории прилавок. `Protector-Owner` добавляет в свой приват ник `Shop-Owner`. `Shop-Owner` устанавливает прилавок на территории `Protector-Owner`.

`Protector-Owner` открывает прилавок и видит:
 - _Сейчас:_ тоже самое как обычный покупатель
 - _Хочется:_ кроме этого видеть:
      - кол-во оставшегося товара на складе
      - дату последнего обновления (покупка/пополнение товара)

**Comment by Mikola314** [comment]
Не вижу в этом надобности. На мой взгляд, прилавок является частным хранилищем игрока.

Допустим, я игрок. Может я на складе прилавка на рынке Нянкетов храню подальше от всех. Зачем мне, как игроку лишнее модерирование со стороны хозяина территории?
 
Куда важнее вылечить баг с отсутствием проверки мета-данных объектов.

**Comment by alek13** [comment]
Интересный ход мысли про хранение Нянкетов... :)
Вполне резонно, но есть другие "за"
> "Не вижу в этом надобности ... ... ..."

Надобность следующая:
Для развития экономики на сервере требуется здоровая конкуренция. Она обеспечивается наличием нескольких торговых мест-площадок (рынков/магазинов/...). Чем их больше, тем лучше. Именно площадок, а не отдельных личных прилавков возле своего дома (ну понятно - туда просто ходить никто не будет). Естественно должен быть и спрос и игроков побольше, но это уже отдельный вопрос. Одному обеспечивать производство и своевременную поставку товаров на все прилавки рынка/магазина достаточно сложно, а я бы сказал невозможно вообще, если ты не модератор. Даже модератору следить допустим за двумя рынками будет сложновато. К тому же если следит и обеспечивает 1 человек, то здоровой конкуренции он не обеспечит. Ну если только у него нет качественного раздвоения личности :) . Т.о. требуется чтобы такие площадки обеспечивали разные люди, и лучше именно игроки, а не модераторы. Во-первых у модераторов и своих дел хватает, во-вторых тогда нужно искать доп. модераторов, в-третьих (а может и в главных) так сам игрокам играть намного интереснее, - т.е. народ долше будет задерживаться на сервере и общее число игроков немного возрастёт (но это опять-таки отдельный вопрос). Итак: если торговую площадку обеспечивает игрок, то (как я уже говорил) сам он не обеспечит своевременной поставкой товара. Если нет своевременной поставки, то площадка станет не интересна другим и в итоге будет заброшена, коих уже полно на сервере. Чтобы не было очередной заброшенной торговой площадки нужно привлекать других игроков, чтобы они ставили свои прилавки и т.о. помогали своевременно обеспечивать товаром и удерживать площадку в рабочем состоянии. Игрокам выгодно немного демпинговать, чтобы у них покупали. Однако это часто приводит просто к пустым прилавкам, т.к. моментально всё скупается, а новой товар игрок не успел произвести. Такой расклад тоже приводит к отсутствию интереса к площадке и в итоге к заброшенной площадке. Чтобы этого не происходило нужен человек, который следит за наличием товара в прилавках и каким-либо образом влияет на их своевременное наполнение. Едиственный кандидат на эту роль - владелец самой площадки, т.е. тот, чья это территория (чьи приваты). Он может просто брать плату по месячно (как это делают уже на нашем сервере), тем самым подстёгивая либо подбирать правильную цену и темп производства, либо ставить прилавки от своего имени и закидывать в них товар а потом отдавать выручку, либо устанавливать какие-либо другие правила. Цель у владельцев площадок одна - чтобы она была дейстующая, к ней всегда был интерес и другие приходили туда. Конечные цели (выручка, просто ему так нравится и т.д.) могут быть разные, но эта цель у всех присутствует. Как раз она и обеспечит здоровую конкурецию на сервере, а значит развитие экономики и более интересный геймплей (интересней играть и владельцам ТП, и продавцам, и покупателям).
Ну и, завершая эту поэму, про надобность: владельцам ТП нужно следить за сотоянием прилавков на площадке и своевременной поставкой товара.

> "...является частным хранилищем игрока.  Может я ... Нянкетов храню..."

Это, конечно, не исключено, но я не думаю, что такие действительно есть. Ну как мимнимум их количество не критично. К тому же полно других вариантов хранить.
Если об этом будут знать, то для таких целей не будут их использовать. Да и стоит он не дёшево, чтобы его просто как сундук использовать.
Но вот предупредить (оповещение вывести или ещё как-то) пожалуй стоит.

> "Зачем мне, как игроку лишнее модерирование со стороны хозяина территории?"
Так это априори его территория и не вижу тут никакого противоречия. Как говориться: "Не хочешь, чтобы тебе что-то сломали или видели остаток в твоём прилавке, не ставь на чужой территории, - привать свою и строй / ставь прилавки там".
Не думаю, что вообще кто-то будет париться по этому поводу.
Вот представь: ты захотел попробовать заняться торговлей и подзаработать; ты понимаешь, что ставить прилавок где-то возле своего дома не резон, а нужно ставить где-то в проходном и известном месте; ок, ты пошёл (например) к Sachiel'ю и попросил разместить у него в магазине прилавок; тебе говорят "ок, но остаток на складе будет виден ему"; спрорим ты скажешь "да вообще пофиг!"

> "Куда важнее вылечить баг ..."
Так его и его важность никто не отменял.
Да и других более важных задач набирётся, я думаю, с пару дюжин.
