### ISSUE TITLE
PvP: Lord Bows: extract `controls` mod

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#1550]
https://content.minetest.net/packages/mt-mods/controls/

----
**EDIT:**
**_after research:_**
наш немного лучше, ждать PR нет смысла -- мод маленький переподключиться всегда можно.
оставляем наш, но выносим в отдельный мод

**Comment by Doloment** [comment]
В controls отсутствуют необходимые для луков функции, реализованные в нашем варианте:
registered_on_wield_index_change
register_on_wield_index_change

**Comment by alek13** [comment]
ага, спасибо, учту

**Comment by alek13** [comment]
upd desc
