### ISSUE TITLE
Обновление модов: Факела из minetest_game 0.4.15+ (моделька и метод размещения

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#157]
Красивая модель огня ( Х, а не # как в lord сейчас).

----
_таск создан [из коммента #52-го](https://github.com/lord-server/lord/issues/52#issuecomment-278758178) (раздел "Обновление модов до последних версий") для наглядности хода [проекта](https://github.com/lord-server/lord/projects/6)_

**Comment by Doloment** [comment]
Стоит изменить "0,4,15" на "0.4.15+"

**Comment by alek13** [comment]
не актуально
