### ISSUE TITLE
Исчезающие itemframes или не рабочий areas?

### ISSUE THREAD

**Issue by narrnika** [lord-server/lord#16]
Из-под защиты areas куда-то пропадают рамки (itemframes). По логам пока ничего не видно - видимо события происходили в период, в существующие логи не попавший... а может и вовсе в логи не писались... в общем, ставим на контроль.

**Comment by weqqr** [comment]
Не могу повторить

**Comment by Mikola314** [comment]
причина в https://github.com/lord-server/lord/issues/36
"Головой об стену" или "Куда исчез узел при перезаходе игрока" #36
