### ISSUE TITLE
Обновление модов: ЖД звуки и алгоритм движения с поправкой на паровые двигатели

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#160]
Есть информация,что он менее глючный.

----
_таск создан [из коммента #52-го](https://github.com/lord-server/lord/issues/52#issuecomment-278758178) (раздел "Обновление модов до последних версий") для наглядности хода [проекта](https://github.com/lord-server/lord/projects/6)_

**Comment by Mikola314** [comment]
В оригинальном minetest_game из релиза minetest 5.1 при применении большого количества ускоряющих путей замечены баги с вылетом с пути. Пока игрок рядом с тележками - всё хорошо и красиво. Если оставить катящиеся тележки  и вернуться к ним после исчезновения онлайн-зоны, часть тележек уже улетели с пути.
Алгоритм стабильнее. чем существующий сейчас на lord, но не без багов(

**Comment by alek13** [comment]
Обновлено @albel4'ом в 9e4e9e8bd611674533a4817741a78314bdab8b21 и b77d1733dd5139bedf7d840a54d6d04cded86f75. Релизнуто в [2019.12](https://github.com/lord-server/lord/releases/tag/2019.12)
