### ISSUE TITLE
Плащ клана Ганзы,ломает текстуру персонажа

### ISSUE THREAD

**Issue by Petus228666** [lord-server/lord#1604]
Плащ клана Ганзы,ломает текстуру персонажа
![screenshot_20240803_125815](https://github.com/user-attachments/assets/35186103-3154-406c-906a-bfea161b63f7)

Как воспроизвести:

Шаги воспроизведения на боевом:

1. Достаём (команда `/list`) "плащ ганзы"
2. Берём плащ
3. Открываем инвентарь
4. Устанавливаем в слот для плащей
5. в чате ошибка
6. мы фиолетовые

**Comment by alek13** [comment]
@Petus228666 , с плащами в итоге разобрались ?
Через сундук получилось их обновить ?
