### ISSUE TITLE
Обновление модов: Various/ambience

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#161]
----
_таск создан [из коммента #52-го](https://github.com/lord-server/lord/issues/52#issuecomment-278758178) (раздел "Обновление модов до последних версий") для наглядности хода [проекта](https://github.com/lord-server/lord/projects/6)_

**Comment by ssdaniel24** [comment]
Это тот или не тот: <https://notabug.org/TenPlus1/ambience/>?
