### ISSUE TITLE
В поиске по крафтам tooltip'ы тоже учитываются

### ISSUE THREAD

**Issue by ssdaniel24** [lord-server/lord#1615]
**Описание ошибки:**

При поиске по крафтам в соответствующей книжке крафтов в результатах значатся несовпадающие по названию предметы, которые не должны показываться по данному запросу.

![image](https://github.com/user-attachments/assets/de655174-60d6-4088-9512-44572663d658)

**Как воспроизвести:**

Шаги воспроизведения:

1. Открываем master_book по крафтам.
2. Вводим "блок"
3. Видим, что помимо блоков на последних страницах появляются инструменты, в названиях которых нет "блок"а, однако есть в описании предмета.

**Ожидаемое поведение:**

Поиск происходит только по названию предмета.

**Comment by Doloment** [comment]
Технически, не баг, а фича :D Это побочный эффект того, что подсказки всё так же считаются описанием предмета, а по нему выполняется поиск. Если это поведение не устраивает, тогда можно выпилить, но надо переделать механизм поиска

**Comment by alek13** [comment]
так и задумывалось, если будет и правда мешать, то поменяем поиск.
на данный момент закрываю.
