### ISSUE TITLE
Увеличение производительности карты путем замены nodebox на mesh

### ISSUE THREAD

**Issue by googolgl** [lord-server/lord#164]
Отличные от куба объекты созданные как nodebox нагружают сервер сильнее.
Если заменить след фигуры на mesh c файлами .obj:
- [ ] Полублок
- [ ] Ступенька
Проседания по скорости должны уйти.

**Comment by ssdaniel24** [comment]
Придётся писать в `_overwrites` свою функцию создания ступенек и полублоков, так как в самой функции MTG `stairs.register_stair_and_slab` используется nodebox:
```lua
drawtype = "nodebox",
```
[В коде](https://github.com/minetest/minetest_game/blob/d775a9bdaeaa20f271baf07abf75cd737b3fc573/mods/stairs/init.lua#L105).

**Comment by ssdaniel24** [comment]
[Оптимизации не будет](https://forum.minetest.net/viewtopic.php?t=19413). А еще всё равно nodebox'ы конвертируются в мэши.
