### ISSUE TITLE
Гобелен кланов имеет не правильную коллизию

### ISSUE THREAD

**Issue by Petus228666** [lord-server/lord#1645]
Показательный гобелен кланов имеет слишком большую коллизию,а точнее целый невидимы блок,через который нельзя пройти 

Относится к #1393 
Как воспроизвести:

Шаги воспроизведения

1. Достаём показательный гобелен кланов
2.  ставим перед собой на любую поверхность
3. пытаемся пройти около гобелена
4. Упираемся в невидимый блок 

Ожидаемое поведение:коллизия как  у остальных гобеленов,через которые можно проходить

**Comment by alek13** [comment]
@ssdaniel24 , посмотришь что там ?
