### ISSUE TITLE
у достижений типа- "побывать в биоме" при получении нет иконки

### ISSUE THREAD

**Issue by Petus228666** [lord-server/lord#1646]
У достижений для которых необходимо откопать блок  земли,при получении нет текстуры травы биома,в которым вы добыли блок

Шаги воспроизведения:

1. гуляем до ближайшего биома(у меня Дунланд)
2. копаем землю с травой биома
3. получем достижение
4. Видим что текстуры нет,на месте иконки с травой,зеленый квадрат,а в чат приходит сообщение что отсутствует энная текстура

Ожидаемое поведение: при получении достижения, получать его с иконкой травы из биома в котором ты побывал

**Comment by Doloment** [comment]
Связано с #1428
