### ISSUE TITLE
нет перевода на знаке защиты и айтемов с его использованием

### ISSUE THREAD

**Issue by Petus228666** [lord-server/lord#1647]
Знак защиты,и блоки,в крафт которые он входит,не имеют русский перевод

Как воспроизвести:

Шаги воспроизведения:

1. Достаём "sign of protection"
2. Открываем инвентарь
3. Видим что отсутствует перевод

Ожидаемое поведение: перевод на Русский в "знак защиты" и перевод на остальные блоки в которых есть этот айтем

**Comment by alek13** [comment]
@Petus228666 "sign of protection" не находит... :(
как называется нода ?

**Comment by alek13** [comment]
ааа... походу он пофикшен уже
![image](https://github.com/user-attachments/assets/140ba350-9872-4faa-a11e-7224590dfd97)
