### ISSUE TITLE
Странные сообщения в чат

### ISSUE THREAD

**Issue by Petus228666** [lord-server/lord#1648]
Странные сообщения в чат на 17 странице книги "все рецепты"

![Снимок экрана 2024-09-10 165325](https://github.com/user-attachments/assets/0696ac69-5f19-41b9-8b38-d50dca9cd760)

Как воспроизвести:

Шаги воспроизведения на боевом:

1. Достаём книгу- Все рецепты
2. Открываем
3. листаем до 17 страницы 
4. Видим сообщения в чат

Ожидаемое поведение: Чисты чат от ошибок тестур

**Comment by alek13** [comment]
это когда было ? вроде же уже пофиксили.
duplicates #1547
