### ISSUE TITLE
Нет перевода на мече людей

### ISSUE THREAD

**Issue by Petus228666** [lord-server/lord#1660]
На новом мече людей нет перевода на русский

**Как воспроизвести:**

Шаги воспроизведения на тестовом

1. Достаём (команда `/list`) "деревянный меч( human_sword`)
2. Открываем инвентарь
3. нет перевода

Дополнительная информация:перевести на русский

**Comment by Doloment** [comment]
Актуально? @Petus228666

**Comment by Petus228666** [comment]
Не актуально. Закрываю
