### ISSUE TITLE
Разнообразие фоновых рисунков

### ISSUE THREAD

**Issue by narrnika** [lord-server/lord#17]
Есть куча форм (окошек, formspec, кому как больше нравится). И есть к ним куча (чуть поменьше) фоновых рисунков, которые разбросаны по разным модам. При этом распределены эти рисунки по формам довольно хаотично. Кроме того, большая часть этих рисунков довольна светлая, а буквы почти везде белые, на что уже неоднократно жаловались... В общем, предлагаю сюда собрать списки используемых форм и фонов и решить как-то их привести в порядок.

**Comment by narrnika** [comment]
Вот список используемых фонов (м/б какие-то пропустил, напомните - допишу):
https://github.com/weqqr/lord/blob/master/mods/bones/textures/gui_bonesbg.png
https://github.com/weqqr/lord/blob/master/mods/default/textures/gui_chestbg.png
https://github.com/weqqr/lord/blob/master/mods/default/textures/gui_formbg.png
https://github.com/weqqr/lord/blob/master/mods/default/textures/gui_furnacebg.png
https://github.com/weqqr/lord/blob/master/mods/lord_info/textures/info_formbg.png
https://github.com/weqqr/lord/blob/master/mods/lord_mail/textures/mail_bookbg.png
https://github.com/weqqr/lord/blob/master/mods/lord_mail/textures/mail_paperbg.png
https://github.com/weqqr/lord/blob/master/mods/lottarmor/textures/gui_formbg.png
https://github.com/weqqr/lord/blob/master/mods/lottblocks/textures/gui_angmarbg.png
https://github.com/weqqr/lord/blob/master/mods/lottblocks/textures/gui_elfbg.png
https://github.com/weqqr/lord/blob/master/mods/lottblocks/textures/gui_gondorbg.png
https://github.com/weqqr/lord/blob/master/mods/lottblocks/textures/gui_hobbitbg.png
https://github.com/weqqr/lord/blob/master/mods/lottblocks/textures/gui_mordorbg.png
https://github.com/weqqr/lord/blob/master/mods/lottblocks/textures/gui_rohanbg.png
https://github.com/weqqr/lord/blob/master/mods/lottinventory/textures/craft_formbg.png
https://github.com/weqqr/lord/blob/master/mods/lottpotion/textures/gui_brewerbg.png

**Comment by TheEagleEye** [comment]
В чем проблема использовать один единственный фон для всех интерфейсов?

**Comment by Mikola314** [comment]
"В чем проблема использовать один единственный фон для всех интерфейсов? " - вот и я об этом

**Comment by TheEagleEye** [comment]
Вон даже взять info_formbg.png 16.5 кб, вместо тех которые по 200кб*количество фонов.

**Comment by alek13** [comment]
не актуально
