### ISSUE TITLE
chest sorting clears paintings and other meta

### ISSUE THREAD

**Issue by ssdaniel24** [lord-server/lord#1711]
**Описание ошибки:**

Сортировка в сундуках вызывает перезапись метаданных предметов, а значит и потерю информации в картинах.

![image](https://github.com/user-attachments/assets/0c4f0e7e-a74b-4429-91be-7c81496c1dc9)
![image](https://github.com/user-attachments/assets/a096dacf-a4bb-42e4-8557-c136e5bf3e8f)
*Скриншоты от игрока Swed.*

**Как воспроизвести:**

1. Взять несколько разных картин.
2. Положить в пустой сундук с возможностью сортировки в разном порядке (не в первых слотах).
3. Нажать "Сортировка".
4. Взять картины и поставить их.
5. Увидеть, что они пусты.

**Ожидаемое поведение:**

5. Увидеть те же самые картины, что клали до этого.

**Дополнительная информация:**

Возможно связано с #1199. Происходит перезапись метаданных, а значит сортировка в сундуке происходит неправильно, затирая их эти самые метаданные... Needs research.

**Comment by alek13** [comment]
названия книг тоже пропадают

**Comment by Doloment** [comment]
Тоже самое с содержанием свитков
