### ISSUE TITLE
Текст на странице информации выходит за рамки

### ISSUE THREAD

**Issue by Doloment** [lord-server/lord#1717]
полный скрин не прикрепляю, чисто потому что
![image](https://github.com/user-attachments/assets/e2dd5331-d495-44fb-9c1c-657ac9d59436)

**Comment by alek13** [comment]
ага, есть такая трабла.
Relates to #1709
а это на каком разрешении так ?

**Comment by Doloment** [comment]
![image](https://github.com/user-attachments/assets/9344a4f0-2fa0-4162-a6e4-d8369c6d0ad4)

**Comment by alek13** [comment]
оч странно у мне на том же разрешении:
![image](https://github.com/user-attachments/assets/30348f8b-cba4-4cbd-b448-8e83d21c6f2c)

**Comment by Doloment** [comment]
А, размер шрифта стоял 18
полагаю, invalid

**Comment by alek13** [comment]
ну почему же, пожалуй стоит указывать точный размер шрифта, а не относительный.
форму в любом случае придётся переделывать.
Но, наверное, когда ui зарелизят.
Я, если честно задолбался с этим кривож....ым formspec'ом

**Comment by alek13** [comment]
ок, добавлю в
#1709
