### ISSUE TITLE
MS-2019.01: при стрельбе практически в упор, попадание примерно 1 раз из 3-х

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#175]
при тестировании #78 
- попадание примерно 1 раз из 3-х
- стрельба сквозь стены ([см. коммент](https://github.com/lord-server/lord/issues/175#issuecomment-461975606))

**Comment by vladtcvs** [comment]
https://github.com/lord-server/lord/pull/179 исправляет проблему, что стрела пролетает насквозь цели и не попадает в нее

**Comment by vladtcvs** [comment]
При стрельбе совсем в упор проблема иногда наблюдается, т.к. стрела образуется на некотором расстоянии от стреляющего

**Comment by vladtcvs** [comment]
Но это можно считать, что ты не смог правильно выстрелить, если арбалет уперся в цель

**Comment by alek13** [comment]
видать по той же причине есть возможность стрелять сквозь стены, если находишься вупор к стене или даже на расстоянии метра или полутора

**Comment by vladtcvs** [comment]
Исправлено в https://github.com/lord-server/lord/pull/190

**Comment by vladtcvs** [comment]
Проверьте пожалуйста работу и закройте, если ок
