### ISSUE TITLE
MS-2019.01: Нет звуков воды

### ISSUE THREAD

**Issue by Doloment** [lord-server/lord#176]
Хз почему. На тестовом сервере я не наблюдал звуки воды, причем сейчас на Л.О.Р.Д. звуки есть

**Comment by vladtcvs** [comment]
на тестовом звуки воды есть

**Comment by vladtcvs** [comment]
Вот при локальном запуск действительно почему то не звуков

**Comment by vladtcvs** [comment]
Звуки в lord_ext, локально его забыл поставить
