### ISSUE TITLE
Таблцу крафтов во внешний файл

### ISSUE THREAD

**Issue by narrnika** [lord-server/lord#18]
Появилась следующая идея:
при старте сервера писать все регистрируемые крафты в отдельный файл, дабы потом удобней было контролировать, что есть, чего не хватает, где какие косяки имеются... в первом приближении реализация выглядит следующим образом:
```lua
local file_name = minetest.get_worldpath() .. "/craft.list"

local file = io.open(file_name, "w")
io.close(file)

local old_register_craft = minetest.register_craft

function minetest.register_craft(craft_table)
	local file = io.open(file_name, "a")
	file:write(minetest.serialize(craft_table).."\n")
	io.close(file)
	return old_register_craft(craft_table)
end
```
Вопрос: 
надо ли нам такое, и если да, то в какой формат и в каком виде лучше писать, чтоб потом было удобнее читать?

**Comment by weqqr** [comment]
Я бы вынес все крафты в отдельную таблицу, из которой они регистрируются с помощью `for`. Так и читать удобнее, и редактировать. К примеру (на работоспособность не проверял):
```lua
some_mod.craft = {
        {
                output = "some_mod:foo",
                recipe = {
                        {"default:wood", "default:wood", "default:wood"},
                        {"default:wood", "default:stone", "default:wood"},
                        {"default:wood", "default:wood", "default:wood"} 
                }
        },
        { 
                output = "some_mod:bar",
                recipe = {
                        {"default:wood", "default:wood", "default:wood"},
                        {"default:wood", "default:wood", "default:wood"},
                        {"default:wood", "default:wood", "default:wood"}
                }
        },
}

for _, craft in ipairs(some_mod.craft) do
        minetest.register_craft(craft)
end
```

**Comment by narrnika** [comment]
Да, так то же можно.. Тогда моё предложение можно будет использовать только один раз для формирования самой таблицы. Редактировать полученный файл действительно будет удобней, правда при этом развернуться уже существующие циклы (к примеру, из мода dye) и функции (см., например, stairs).

**Comment by narrnika** [comment]
Вариант номер два:
https://github.com/narrnika/extract_craft_table/blob/master/init.lua
и результат его работы в дефолтной minetest_game:
https://github.com/narrnika/extract_craft_table/blob/master/craft_table.lua.txt
Кажется, вышло несколько растянуто и для дальнейшей работы с таким монстром его ещё надо облагородить, но так, пожалуй, лучше, чем однострочный вариант от serialize...

**Comment by weqqr** [comment]
Думаю, следует каждый мод писать отдельно. Тогда и файлов в пять тысяч строк удастся избежать.

**Comment by narrnika** [comment]
В смысле - с каждого мода в отдельный файл modname.lua, а потом все эти файлы через dofile() в init.lua? Можно, конечно, и так... 
Впрочем, меня больше беспокоит то, что записать все крафты можно (куда угодно, хоть в один файл, хоть в несколько) автоматически, а вот вырезать их все из модов придётся вручную...

**Comment by weqqr** [comment]
Да, по файлу на каждый мод. Делать что-либо вручную придётся в _любом_ случае.

**Comment by narrnika** [comment]
> Делать что-либо вручную придётся в любом случае.

Ну, тут я не спорю ни разу... а вот насчёт "по файлу на каждый мод" - попробовал сейчас, default вернул 1400 строк, stairs - 1000... это конечно не 5000, но то же не фэншуй...

**Comment by weqqr** [comment]
С default так и должно быть, а вот выносить stairs - далеко не самая лучшая идея (потому что там всего лишь пара схем крафта, в которые подставляются значения).

**Comment by narrnika** [comment]
И что их теперь, оставить в родном моде? Тогда не вижу смысла выносить остальные - всё равно часть там лежит, часть тут... Можно, конечно, перепаковать их в цикл уже на новом месте, но для этого надо принять откуда-нибудь таблицу подставляемых материалов..

**Comment by albel4** [comment]
Таблицу крафта в каждом моде в отдельный файл можно, а вот все вместе сливать не нужно. Я вообще за то, чтобы моды были независимыми, по-возможности разумеется.

**Comment by weqqr** [comment]
Идея нежизнеспособна
