### ISSUE TITLE
MS-2019.01: Throwing Engine: практически любой моб убивается с одного выстрела мифриловым болтом

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#181]
при тестировании #78

**Comment by alek13** [comment]
проблема осталась

**Comment by vladtcvs** [comment]
Урон от мифрилового болта существенно уменьшен

**Comment by vladtcvs** [comment]
Не до почти нуля же его снижать?
Кому он нужен тогда будет?

**Comment by vladtcvs** [comment]
Вроде бы исправлено

**Comment by alek13** [comment]
Урон стал меньше, но по моим ощущениям всё-равно много.
@Mikola314 , @googolgl , @weqqr , можете тоже взглянуть.
Мне кажется урон от мифрилового болта стал великоват (по сравнению с боевым)

**Comment by alek13** [comment]
@vladtcvs :
сейчас такой урон:
стальная стрела - 3 единицы
мифриловая стрела - 12 единиц
стальной болт - 36 единиц
мифриловый болт - 72
могу болты в 2 раза ослабить

@alek13 :
ну может не в 2, но (как по мне) ослабить нужно

**Comment by vladtcvs** [comment]
> стальной болт - 36 единиц
> мифриловый болт - 72

стало


стальной болт - 18 единиц
мифриловый болт - 36

**Comment by alek13** [comment]
уменьшили до текущих значений на боевом.
изменение урона будем делать в рамках ребалансировки оружия.
