### ISSUE TITLE
Моментальная готовка зелий/алкоголя

### ISSUE THREAD

**Issue by Petus228666** [lord-server/lord#1834]
Если в бочку/лабораторию по рецептам положить ингредиенты в слоты,то первое зелье/алкогольный напиток приготовится моментально

Как воспроизвести: смотрите видео ниже

https://github.com/user-attachments/assets/08569624-161e-49c1-bfe1-dab34842350f

Ожидаемое поведение: Все готовится с таймером,независимо от того как по очереди идет приготовление

Было описано в #1826

**Comment by alek13** [comment]
круто!...  огонь баг... ~щет~
