### ISSUE TITLE
Новые текстуры оружия и инструментов: залить на тестовый

### ISSUE THREAD

**Issue by TyulenPelmen** [lord-server/lord#1843]
Приведены к единообразию палитры. Формы корректированы для большей наглядности и различимости.

[NEWINSTRUMENTARY.zip](https://github.com/user-attachments/files/18137431/NEWINSTRUMENTARY.zip)
[NEWWEAPONRY.zip](https://github.com/user-attachments/files/18137432/NEWWEAPONRY.zip)

**Comment by alek13** [comment]
новый вариант перезалит в #1877
