### ISSUE TITLE
Некорректное отображение текстуры бутыльков в форме центрифуги

### ISSUE THREAD

**Issue by Doloment** [lord-server/lord#1851]
На месте пропавшего изображения должна была быть текстура бутылька
![image](https://github.com/user-attachments/assets/528fe259-2bbb-4433-b65e-35d01cdf50f3)

**Comment by alek13** [comment]
так.... это походу старые...
у только поставленных всё ок:
![image](https://github.com/user-attachments/assets/36ae8bf1-8ae1-4243-8d82-aa9a6a9ca662)
