### ISSUE TITLE
Обработка исключений в коде игрока и мобов

### ISSUE THREAD

**Issue by vladtcvs** [lord-server/lord#1872]
**Проблема:**

Ошибка в моде приводит к падению сервера

**Предложение:**

Обернуть код мобов игроков, как минимум тот, который вызывается по `on_step()` в обработчик исключений. Иначе подключение игрока, который находится в локации с багающим мобом или с багом в обработке его самого, приводит к моментальному падению сервера

ABM для нод тоже желательно обернуть обработчиками

**Comment by vladtcvs** [comment]
Понятно что в идеале багов быть не должно. Но все же когда от каждого бага падает весь сервер - это не круто.

**Comment by vladtcvs** [comment]
Последствия бага должны быть локализованы тем объектом (игроком, мобом), в котором возник баг

**Comment by alek13** [comment]
логи кто-нибудь смотрел ?
откуда такие выводы ?

**Comment by alek13** [comment]
что-то я не припомню в lua эксепшенов.
перелопачивать весь мод пытаясь найти там не обработанные `nil` и т.п. -- думаю не самая лучшая затея, учитывая, что это на 99% не оно и загрузку команды.
есть более полезные вещи.
