### ISSUE TITLE
Пересборка LORD - что, куда и как?

### ISSUE THREAD

**Issue by narrnika** [lord-server/lord#19]
Что оставляем в ядре (subgame), что выносим отдельно (в mods), что (возможно) для этого переделываем? Мнения, концепт-модели, рацпредложения - всё сюда:

**Comment by albel4** [comment]
исключаем из ядра:
ambience
bees
defaults (не default)
dumpnodes
itemframes
protector_lott (по-возможности)
signs_lib
techinc_chest
teleport_request
torches
walking_light

**Comment by narrnika** [comment]
Странно, вроде ж говорили, что выносить будем то, что не содержит блоков и предметов, т.е. чьё удаление не породит unknownitem... я не настаиваю именно на таком варианте, просто уточнить хочу...

Конкретно по предложенному списку:
- однозначно поддержу вынос ambience, walking_light, teleport_request;
- насчёт torches - есть сомнения, вроде мы его к картогенеру прикручивали, после удаления может засбоить;
- protector_lott - я бы оставил в ядре механизм защиты, функции регистрации дверей, блоков, ящиков и т.д., а вызовы этих функций с конкретными параметрами вынес бы в mods - отдельным модом, либо раскидав по тем, чьи материалы используются (собственно, аналогично я поступил бы и с signs_lib, и с itemframes, и со многими другими модами, дающими не просто декоративный, а рабочий материал);
- dumpnodes - объясните, что это, я его первый раз вижу 8-0 ;

Так же предлагаю вынести следующее:
mp_world_edit;
mega_sl;
mail_list;
creative (собственно, я вообще не понимаю, зачем нам это);
lists;
sethome.

Это - при любом раскладе, насчёт остального - я так понимаю, стоит ещё определиться, по какому принципу мы всё это пересобираем...

**Comment by weqqr** [comment]
Вынести:
- ambience
- mp_world_edit
- mega_sl
- lists (кстати, что оно на сервере забыло?)
- lord_base_commands
- lord_base_privs
- lord_mail
- lord_names_rules
- mail_list
- sethome
- spawn
- teleport_request
- walking_light

Удалить:
- dumpnodes

**Comment by narrnika** [comment]
Кстати, в weqqr/lord каталог mods уже есть... куда выносить-то будем?

**Comment by weqqr** [comment]
```
Mod load path
-------------
Generic:
...
* `$path_user/games/gameid/mods/`          <- моды в subgame
* `$path_user/mods/` (User-installed mods) <- выносить сюда
* `$worldpath/worldmods/`                  <- моды, специфичные для мира (у нас таких нет)
```

**Comment by narrnika** [comment]
Да не, где это на сервере будет лежать, я понимаю, не совсем понятно, как это лучше на github'е оформить.
Кстати, не знал, что моды можно прямо в каталоге мира хранить...
