### ISSUE TITLE
Сломалась регистрация призрачных материалов

### ISSUE THREAD

**Issue by vladtcvs** [lord-server/lord#192]
пропал defaults:default_brick

**Comment by vladtcvs** [comment]
Самым невероятным образом, git bisect указал на 880ba78c78c7a7dccfc32769847aeb912e304ea7

**Comment by vladtcvs** [comment]
проблему почему-то вызывает

`minetest.register_node(name.."_axe_box", {...})`

**Comment by alek13** [comment]
> проблему почему-то вызывает
> 
> `minetest.register_node(name.."_axe_box", {...})`

Проблема возникала не из-за этого.
Сама регистрация призрачных блоков содержала баг,
который раньше не всплывал
(точнее всплывал, но затрагивал совсем мало блоков и был не замечен)

**Comment by alek13** [comment]
протестировано Владом ( @vladtcvs )
