### ISSUE TITLE
MS-2019.01: Throwing Engine: Поразивший цель болт, остаётся лежать рядом

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#197]
При тестировании #78 .
Не всегда, но через раз точно, болт, который только что поразил цель, остаётся лежать вместо убитого моба, как-будто дроп.

**Comment by alek13** [comment]
При попытках воспроизвести баг и понять в каких случаях это происходит, пришёл к такому выводу:

похоже, что при:
- выстреле немного сверху и попадании в ноги (когда земля/пол рядом с точкой попадания в моба)

или при:
- выстреле прямо, но моб у стены (когда стена рядом с точкой попадания в моба)

Т.е. ощущение, что после попадания в моба, стрела продолжает лететь, попадает в стену(пол) и дропается, но при этом и успевает нанести урон мобу.
Те же ощущения (что стрела продолжает лететь) при выстреле сквозь стену в #196

**Comment by vladtcvs** [comment]
Да, это происходит, если стрела одновременно поразила и моба и ноду.
