### ISSUE TITLE
MS-2019.01: Throwing Engine: Дуга полёта и вес болта/стрелы

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#198]
При тестировании #78 .
Дуга полёта болтов и стрел слишком изогнута.
Т.е. при полёте болт слишком быстро теряет высоту.
Это явно зависит от неправильно выбранного веса стрелы/болта.
(и похоже аффектит на урон)

Вес стрелы примерно 500гран (**32,5 грамма**). **Сейчас** стоит пол килограмма - это _7716 гран (**500г**)_.

Вес современных стрел:

| Arrow                              | Weight                    | Point | Total Grs | Speed (Ft/s) | Kinetic energy ft/lbs |
| ------------------------------- | --------------------------- | ----- | ----- | --------------------- | ------------------------ |
| Barnett 22"(Easton C2)    | 320 (**20.74грамм**) | 100 | 420 | 384.2 | 137.7 |
| Barnett 22"(Easton C2)    | 320(**20.74г**)           | 125 | 445 | 376.2 | 139.8 Factory Setup |
| Beman Thunderbolt 20" * | 295(**19.12г**)           | 125 | 420 | 384.4 | 137.8 |
| Easton Power Bolt 20*      | 327(**21.19г**)           | 125 | 452 | 365.8 | 134.3 |
| Horton 20" *                      | 435(**28.19г**)           | 125 | 560 | 342.9 | 146.2 |

ещё (зависимость веса и скорости):

| #  | Стрела                                      | вес стрелы, граны(граммы) | скорость, фпс |
| -- | ---------------------------------------- | ------------------------------------ | ------------------ |
| 1. | Грозеровский Sport Longbow I | 520(**33.7**)                          | 168                  |
|     |                                                   | 413(**26.76**)                        | 180                  |
|     |                                                   | 302(**19.57**)                        | 200                  |
| 2. | Корейский Wind Fighter 60       | 520(**33.7**)                          | 183                 |
|     |                                                   | 413(**26.76**)                         | 200                 |
|     |                                                   | 302(**19.57**)                         | 220                 |

**Comment by vladtcvs** [comment]
У нас в игре вообще странное восприятие расстояния.
