### ISSUE TITLE
MS-2019.01: Throwing Engine: Похоже неверно выбран таймер для полёта стрел.

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#199]
Относится к #78 

Есть ощущение, что наслаивается несколько обработок стрел при полёте, что влечёт за собой
- и стрельбу сквозь стены (#196)
- и дроп стрелы после поражения цели (#197)
- и поражение нескольких целей одной стрелой (#195)

нужно поисследовать и проверить.
или что-то похожее.

**Comment by vladtcvs** [comment]
Причины проблемы были в другом, поражались все цели на пути между текущим положением стрелы и следующим
