### ISSUE TITLE
Throwing Engine

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#200]
Универсальный метательно-бросательно-пулятельный движок by @vladtcvs 

Первоначально был реализован в PR #78 .
Также к задаче относятся:
- #139 
- #174 
- #175 
- #180 
- #181 
- #190 
- #191 
- #195 
- #196 
- #197 
- #198 
- #199 

(задача создана для трекинга и закрепления(pin) во вкладке [Issues](https://github.com/lord-server/lord/issues)

**Comment by vladtcvs** [comment]
176 при чем тут?

**Comment by alek13** [comment]
да, - ошибся.
убрал из списка

**Comment by alek13** [comment]
протестировали, все под-задачи/баги закрыты, движок готов.
