### ISSUE TITLE
Лучше учитывать столкновения стрел друг с другом

### ISSUE THREAD

**Issue by vladtcvs** [lord-server/lord#205]
Если 2 стрелы сталкиваются, они обе должны дропаться или поражать друг друга. Сейчас поведение не такое, одна стрела поражает другую. а обратно нет.

**Comment by alek13** [comment]
нужно чтобы они просто сквозь друг друга пролетали.

_ps: можно добавить в PR #292_

**Comment by Doloment** [comment]
Сделано или отложено?

**Comment by alek13** [comment]
отказались https://github.com/lord-server/lord/issues/218#issuecomment-831525958
