### ISSUE TITLE
Текстуры бронзы и меди

### ISSUE THREAD

**Issue by Doloment** [lord-server/lord#216]
Вот такие медь и бронза IRL:
Медь![copper](https://user-images.githubusercontent.com/22934348/53818498-bd014000-3f9a-11e9-8c49-ff23e9263b16.jpg)
Бронза![bronze](https://user-images.githubusercontent.com/22934348/53818499-bd99d680-3f9a-11e9-8769-afa0ff91ef36.jpg)
Какие они у нас:
Медь![default](https://user-images.githubusercontent.com/22934348/53818825-4ca6ee80-3f9b-11e9-82ae-1f02374fd9a9.png)
Бронза![default](https://user-images.githubusercontent.com/22934348/53818826-4ca6ee80-3f9b-11e9-90da-1727d2b28c66.png)
Какими их стоит сделать:
Медь![default](https://user-images.githubusercontent.com/22934348/53818864-60525500-3f9b-11e9-8e86-5b6644fa2da7.png)
Бронза![default](https://user-images.githubusercontent.com/22934348/53818863-60525500-3f9b-11e9-9cc3-d157166c1a38.png)

**Comment by vladtcvs** [comment]
Бронза бывает ОЧЕНЬ разной. оловянная бронза 

Например:
![image](https://user-images.githubusercontent.com/3390973/53825019-5f62f880-3f86-11e9-8eab-b9082fec42ba.png)

![image](https://user-images.githubusercontent.com/3390973/53825062-77d31300-3f86-11e9-97d4-e6c9eeaca242.png)

и др.

**Comment by Mikola314** [comment]
Медь однозначно перекрашивать.
С бронзой сложнее. Если есть желание, можно перекрасить.
> Бронза бывает ОЧЕНЬ разной.

Главное, чтобы бронза была темнее золота.

**Comment by VanicGame** [comment]
Если я не ошибаюсь, слитки (новые) придерживаются этого issue.

**Comment by alek13** [comment]
@Doloment , это закрою, т.к. явно оно уже не актуально. Да и броньки перерисовали с теми же оттенками.
Если считаешь, что оно ещё нужно и оно того стоит, то давай в [#textures](https://discord.com/channels/268093825975713793/554311282271059978) обсудим вместе с Васей
