### ISSUE TITLE
Оптимизировать расчет столкновений для стрел

### ISSUE THREAD

**Issue by vladtcvs** [lord-server/lord#218]
Сейчас стрелы перемещаются с шагом 0.1 для точного учета столкновений. При этом на каждом шаге проверяется, не внутри ли мы collision box моба или игрока. Надо увеличить шаг и проверять, не пересекается ли вектор скорости с collision box

**Comment by Doloment** [comment]
Сделано?

**Comment by alek13** [comment]
от столкновений стрел отказались, сейчас стрелы пролетаю друг друга насквозь
