### ISSUE TITLE
32x Текстуры каменных блоков (природных)

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#223]
- оставить цветовую гамму материала (для единого стиля/цвета с изделиями)
- желательно похоже на изначальную

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
Знаете мне честно говоря нравится именно 16x16...
Я видел другие сервера где сделали текстуры с большем разрешением, оно явно плохо.
И могу четко объяснить почему:

Кубик -- это очень большая условность. 

Для меня проблема большинства 3D игр в том что они стремятся к максимальной реалистичности, и  ее не достигают (подозреваю что в ближайшее время за приемлимые деньги это будет невозможно) . И отклонения от реалистичности сильно режет глаз..

С другой стороны наш мозг на самом деле оперирует абстракциями. Своего рода символами. Поэтому если предложить ему не реалистичную картинку, а  символ, то он его достроит внутри себя до идеальной картины, при этом именно идеальной именно для конкретного потребителя... 

В этом как раз была одна из киллер-фич майнкрафта которые мало кто понимает: за счет использования абстракции и дорендеренга в голове пользователя получается картинка гораздо лучшая чем при рендеренге на графической карте.

Исходя из этого я прихожу к выводу, что текстуры натянутые на кубик должны быть максимально символичными и не стремится к реалистичности. Иначе  из-за хороших текстур из символизма перейдем к визуализму, и вся прелесть уйдет. 

Поэтому я лично против текстур с большим разрешением. Максимум подготовить альтернативынй пак для луюбителей...

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
![Screenshot_20190309_161927](https://user-images.githubusercontent.com/48326335/54072133-6429f400-4287-11e9-8701-da43ab1ec768.jpeg)


Вот такое вот безобразие получается если увлечься разрешением текстур...
Выглядит максимально противоестественно на мой вкус. И это фундаментальная проблема.

**Comment by Mikola314** [comment]
Проблема в том, что в 16х16 пикселей иногда проблематично изобразить то, что задумал. Пример - рабочий стол (автокрафтер) с его 64х64. Я пробовал уменьшить и переработать его текстуры до 32х32 (привести к общему стандарту). Вышло очень плохо и непонятно. 
Когда в мире большое количество разных статичных объектов с одной кубической формой, появляется проблема в визуальном различии этих объектов друг от друга.
Оставлять разные текстуры с разным размером - плохая идея. Практика показала, что находящиеся рядом объекты с разным размером текстур выглядят фигово. Требуется стандартизация. 32х32 является оптимальным вариантом - уже есть простор для рисования, ещё нет "песочности" текстуры.

**Comment by vladtcvs** [comment]
Я для камня предлагаю взять текстуру базальта

**Comment by vladtcvs** [comment]
![image](https://user-images.githubusercontent.com/3390973/54072193-70fb1780-4288-11e9-9573-76755dbbe060.png)

**Comment by vladtcvs** [comment]
Она хорошо подходит к MC, так как базальт и в природе образует столбы

**Comment by Mikola314** [comment]
Вот мои старые наработки, на основе разных текстур-паков https://github.com/lord-server/textures-lord
=

**Comment by vladtcvs** [comment]
Но вообще, даже текущий камень не так уж и плох

**Comment by RodionKarelov** [comment]
У меня как раз есть текстура базальта, только 32х32, могу скинуть

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
Когда я внимательно рассматривал мордорский камень vs оникс только тогда я обнаружил что у них разные разрешения...  Без этого смотрятся достаточно норм...

Главное в этом деле чтобы для между теми объектами большого разрешения и малого разрешения была четкая визуальная граница... Стол более высокого разрешения на фоне пола с более низким разрешением -- норм. А вот если в стену укладывать блоки сильно разных разрешений -- тут будут проблемы...

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
Если переформулировать в рамках исходного высказывания: если деталь носит символический характер, то конечно надо увеличивать разрешение. Но любая деталь которая добавляется строго для реалистичности, или просто из-за того что хочется 32х32 суть зло...

**Comment by Mikola314** [comment]
Если оставить ассорти из размеров, тогда стол с 64х64 и каменная стена с 16х16 так и будут встречаться рядом(

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
Ну тут конечно надо посмотреть на результат, но в целом у меня это противоречия не вызывает. Между ними есть логическое разделение... На передний и заний план например.
Задник на сцене рисуют гораздо менее подробно чем делают костюмы актеров...

Ну короче мы тут ходим по кругу...
Не нравится мне новомодные текстуры и все тут... :-((

**Comment by alek13** [comment]
@nataraj-hates-MS-for-stealing-github , внутри команды уже много раз это осуждалось и все единогласно пришли к выводу, что нужны 32x32.
И да, многие из доводов, которые ты перечисляешь, тоже назывались.
И да, как ты говоришь аля "символический характер" тоже должен присутствовать.
Но и ассорти из разных текстур делать не будем.

Мы будем переносить постепенно все текстуры в разрешение 32x32 в любом случае.

**Comment by Mikola314** [comment]
Могу предложить компромиссный вариант:
В https://github.com/lord-server/lord мы будем внедрять 32х32
Для любителей 16х16 создать отдельный репозиторий с тексур-паком.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
@alek13 ты просто предложил мне этим заняться, а я не то что не хочу, я сильно против... Ну вот об этом я написал...
Ну значит текстуропаки...

**Comment by alek13** [comment]
ок

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
Так, а давайте попробуем зайти с другой стороны,чтобы не совсем все испортить...
Вот такой вариант 32x32 вас бы устроил?

![def_sto](https://user-images.githubusercontent.com/48326335/54077607-d58b9600-42cb-11e9-9598-d2a663f54ba7.jpeg)


![default_stone](https://user-images.githubusercontent.com/48326335/54077615-ecca8380-42cb-11e9-8b07-d7eac117586b.png)

**Comment by vladtcvs** [comment]
Это удвоенный 16x16?

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
Не совсем. Там уложены четыре 16х16  по площади, плюс один посередине...
Там для того чтобы совсем было хорошо, надо еще поиграться, но общее представление оно создает...

**Comment by Doloment** [comment]
Сделал ТП на камень и булыгу.
До изменения:
![screenshot_20190810_223512](https://user-images.githubusercontent.com/22934348/62823785-3db60f00-bbbf-11e9-9c1f-3943d4610a43.png)
После изменения:
![screenshot_20190810_223425](https://user-images.githubusercontent.com/22934348/62823784-3d1d7880-bbbf-11e9-939c-d53ea3d15af9.png)

По-поводу этого:
`Mikola. 31.07.2019
@Doloment. края булыжников слишком контрастные`
На самом деле, это просто кажется. В игре выглядит очень даже хорошо. Может быть немного непривычно, но это со временем пройдет

**Comment by Doloment** [comment]
Неактуально

**Comment by Doloment** [comment]
Неактуально
