### ISSUE TITLE
Драг. камни

### ISSUE THREAD

**Issue by Mikola314** [lord-server/lord#24]
В шахтах много драгоценных камней… Используются только в колечках. Предлагаю использовать их в схемах золотых, и мифриловых сундуков.  Можно в схему Эльфийского меча и в Гномий топор добавить. Можно в Мифриловую броньку добавить..

**Comment by albel4** [comment]
Небольшое уточнение, предлагаю добавлять не сами камни а истолченные в порошок.

**Comment by Mikola314** [comment]
а смысл дробить? Чем крупнее драгоценный камень, тем он ДОРОЖЕ!

**Comment by albel4** [comment]
В сплав камень не положишь. А вот порошочек изумрудный или сапфировый добавить можно.

**Comment by narrnika** [comment]
Порошок - в сплав? Сомнительно, скорее уж что-то типа краски из него сделать - позолоту там, алмазное напыление)) В принципе можно ещё строительные блоки (которые именно блоки, на обрезки лучше не заморачиваться) камнями "украшать", наверное..  Инструменты/оружие - да, пожалуй можно и в виде украшения.

**Comment by Mikola314** [comment]
"Или ты в рамках украшательства предлагал?" именно, а то просто золотой сундук - беспонтово)

**Comment by albel4** [comment]
:)
тогда надо либо текстурку у текущего поправить, либо ещё объект создавать.

**Comment by Mikola314** [comment]
текстурки поправить недолго

**Comment by Doloment** [comment]
Сделано
