### ISSUE TITLE
Идея: Система создания скина персонажа, основанная на конструировании итогового вида персонажа из заранее заготовленных частей.

### ISSUE THREAD

**Issue by Doloment** [lord-server/lord#240]
Существует [данный мод](https://forum.minetest.net/viewtopic.php?t=13138). С его помощью игрок может создать уникальный образ своего персонажа, изменяя и выбирая детали скина непосредственно в игре.

**Плюсы такой системы:**

- У каждого игрока может получится уникальный образ персонажа.
- Благодаря этому расширяются возможности персонализации игрового процесса лично для игроков.

**Минусы:**

- Во время внедрения вместо текущей системы могут возникнуть проблемы с поддержкой скинов игроков, не использующих персонализацию персонажа. Потребуется поддержка старых скинов.

Для выявления остальных особенностей необходимо испытать данную модификацию на новейшей сборке L.O.R.D.

**EDIT:** запустил на MTG. Выглядит красиво. В планах запустить на сборке.

**Comment by Mikola314** [comment]
Каким образом будут формироваться трупы? Сейчас для ноды трупов используется набор, равный всему набору скинов.
