### ISSUE TITLE
Устаревшие depends.txt и description.txt

### ISSUE THREAD

**Issue by Doloment** [lord-server/lord#241]
Использующиеся у нас файлы depends.txt и description.txt в каждом моде устарели с переходом на 5.0. Вместо них следует использовать mod.conf.

Следует в одном из следующих обновлений (или в этом) заменить все вышеупомянутые устаревшие файлы на mod.conf

Стоит отметить, что поддержка устаревших depends.txt и description.txt, скорее всего, не будет когда-либо прекращена. Источник: https://forum.minetest.net/viewtopic.php?f=5&t=21556. Цитата из сообщения модератора rubenwardy:

> by rubenwardy » Tue Dec 11, 2018 21:18
> 
> It's worth noting that depends.txt and description.txt are also deprecated in 5.0.0, but we probably won't ever remove support for them.

**Comment by alek13** [comment]
осталось только в ambience, который подключен submodule'м и при этом в оригинале этого уже нет.
нужно только обновиться.
