### ISSUE TITLE
Неведомая земля

### ISSUE THREAD

**Issue by Mikola314** [lord-server/lord#248]
В заставе Рохана в простом сундуке можно найти  "Legacy Dirt" (legacy:dirt). При установке на землю превращается в "Земля" (default:dirt). В креативном режиме после установки нод legacy:dirt исчезает через секунду.

Заменить упоминания legacy:dirt в сундуках данжей на default:dirt.

**Comment by alek13** [comment]
Актуальна, даже есть в коде:
```
mods/lord/legacy/init.lua:8
mods/lord/legacy/init.lua:14
mods/lord/legacy/init.lua:225
```
дополнительно нужно проветить саму Заставу Рохана (схематик, спаунеры сундуков,..)

**Comment by alek13** [comment]
выпилил в коде, добавил алиас, однако в схематиках обычным поиском не нашлось, нужно отдельно посмотреть повнимательнее сам схематик и спаунеры сундуков в них.
https://github.com/alek13/lord/commit/0c64a5fe55e7a82ca34cdd075e665e419950eda7#comments
