### ISSUE TITLE
Нарсил и призраки

### ISSUE THREAD

**Issue by Mikola314** [lord-server/lord#25]
- [ ] Есть меч tools:sword_elven “Эльфийский меч”, есть мобы - призраки (жители заброшенных подземок и катакомб). Этих мобов ничем не убить. По сценарию против них (да и любых мобов) хорошо идёт Нарсил.
- [ ] Есть мнение, что стоит сделать аналогично для назгулов. Они тоже не живые уже... Только назгулов сделать редкими.
- [ ] С учётом правок стоит усложнить крафт меча (ювелирные камни и мифрил)

**Comment by TheEagleEye** [comment]
Ты хочешь сделать етих мобов убиваемыми мечом “Эльфийский меч”?

**Comment by Mikola314** [comment]
TheEagleEye, да.

**Comment by vladtcvs** [comment]
Сейчас эти мобы выключены чтоли? Ни разу не встречал на сервере

**Comment by vladtcvs** [comment]
Нарсил != эльфийский меч.

Жало и Гламдринг (меч Гэндальфа) также были эльфийскими. Нарсил на призраков действовал потому, что это был меч Исилдура, которому призраки (бывшие тогда людьми) поклялись в верности и предали его.

**Comment by vladtcvs** [comment]
Что до призраков, сейчас они у нас легко убиваются солнечным светом, что не соответствует канону.

**Comment by Mikola314** [comment]
vladtcvs "Сейчас эти мобы выключены чтоли? Ни разу не встречал на сервере" Нет. Они появляются в катакомбах на глубине. HP=1, но их фиг убьёшь.

**Comment by vladtcvs** [comment]
Не видел, хотя был в катакомбах

**Comment by Mikola314** [comment]
vladtcvs, https://vk.com/photo-110633545_439014984

**Comment by vladtcvs** [comment]
Как они выглядят, я знаю) Но не встречал ни разу
