### ISSUE TITLE
Самозатачивающееся оружие

### ISSUE THREAD

**Issue by Mikola314** [lord-server/lord#252]
**Описание ошибки:**

При ударах оружием по мобам, оружие не портится.

**Как воспроизвести:**

Шаги воспроизведения на *[полигоне:30004 (mt_master)]*:
1. Открываем инвентарь.
2. Берём не метательное и не стрелковое оружие (меч, боевой молот, копьё, нож).
3. Активируем слот с оружием.
4. Атакуем любого убиваемого моба выбранным оружием.
5. Во время атаки на моба оружие получает повреждения и сразу восстанавливает его на прежний уровень.
6. При срезании веток оружие получает повреждения и не восстанавливается.
7. Если атаковать моба повреждённым оружием, оружие не получает новых повреждений.

**Ожидаемое поведение:**

Во время атаки на моба оружие должно получать повреждения, не восстанавливая его на прежний уровень.

**Информация о клиенте:**

 - Операционная система: [Windows]
 - Версия клиента: [5.1]
 - Устройство: [ПК]

**Дополнительная информация:**

Оружие восстанавливает прежний уровень повреждения очень быстро.

**Comment by Doloment** [comment]
Баг не замечен. Возможно, то что было принято за восстановление повреждения оружия есть контраст низкого уровня наносимых прочности оружия повреждений при убийстве моба и высокого уровня наносимых прочности оружия повреждений при ломании листвы.

**Comment by Doloment** [comment]
Но, на самом деле, прочность при нанесении урона мобу тратится чересчур медленно.

**Comment by VanicGame** [comment]
Так, подтверждаю, что бронзовый боевой топор, а так же железный и серебряный мечи не теряют прочность, вот замечено было вчера/позавчера на полигоне. Хотел написать об ошибке, а тут уже писали.
Только что проверял деревянный меч, полоска повреждений появлятся, но тут же исчезает, всё, как описано Миколой.

**Comment by VanicGame** [comment]
Проверял баг у себя локально. Не работает. Система FreeBSD. Версия МТ 5.4.1.

Читал документацию и лазил по MineClone, нашел Punch attack uses. В доках написано, что определяет сколько прочности будет у оружия, если им бить по объектам. Прим. только для tool.
В MineClone этот параметр указан. На сайте (в примере), по которому я проходил "обучение" - нет. В наших модах так же не указан.

Я не знаю, целесообразно ли исправлять данный баг, ведь он работает только на полигоне.

**Comment by Doloment** [comment]
Нашел причину в default/functions.lua:

```lua
minetest.register_on_punchplayer(function(player, hitter, time_from_last_punch, tool_capabilities)
	local weapon = hitter:get_wielded_item()
	if tool_capabilities ~= nil then
		local wear = ((tool_capabilities.full_punch_interval or 1.4) / 75) * 9000
		weapon:add_wear(wear)
		hitter:set_wielded_item(weapon)
	end
end)```

Решается обновлением default

**Comment by Doloment** [comment]
Очень странная вещь, похоже это только при ударе игрока срабатывает. Не пойму тогда почему этот баг есть. Если он и правда только на полигоне робит — стоит закрыть задачу

**Comment by VanicGame** [comment]
Мы не смогли выявить причину (вроде как)
