### ISSUE TITLE
Обновить модель листьев

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#284]
- https://github.com/lord-server/b13/blob/main/mods/media/core/models/leaves.obj
 - https://github.com/lord-server/lord/blob/master/mods/_lott/lottplants/models/leaves_model.obj

**Comment by kevicky9** [comment]
Новое/старое:
![screenshot](https://user-images.githubusercontent.com/85643907/142407091-2afbf293-2d21-4ac9-93e7-be9868b9f3ab.jpg)

**Comment by kevicky9** [comment]
Обновить модельку после #350

**Comment by Doloment** [comment]
На созвоне решили не реализовывать: много полигонов, может угробить спаун
