### ISSUE TITLE
Возрождение на месте смерти

### ISSUE THREAD

**Issue by VanicGame** [lord-server/lord#290]
**Описание ошибки:**

Респавн игрока на том же месте, где и умер.

[<Добавьте скриншот из игры, просто перетащив или скопировав (ctrl+v) его сюда>]

**Как воспроизвести:**

Шаги воспроизведения на *[<сервере|полигоне|локальном окружении|копии мира>]*:
1. Умираем
2. Выходим из игры
3. Заходим
4. Нажимаем esc (как я нажал) или возродится (не знаю, сработает ли)
5. Возрождаемся на месте смерти
**Ожидаемое поведение:**

Возродится где-то в Aute-Caras'е, хотя я не понимаю, почему появляюсь там. Вроде спал на других кроватях, а всё равно.

**Информация о клиенте:**

 - OS: FreeBSD
 - Client version: 5.3
 - Device: ПК

**Дополнительная нформация:**

Очень полезный баг, кстати:)

**Comment by vladtcvs** [comment]
> Очень полезный баг, кстати:)

или нет, если умер в лаве
