### ISSUE TITLE
Моб "меняла"

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#308]
- не крафтится, только из админской "сумки"
 - нет в креативном инвентаре
 - форма настройки доступна только для акк с привилегией `server`
 - в этой форме настраеваем из-под админа (прив. `server`):
   - имя
   - текст приветствия/рассказа
   - что меняем (что нужно мобу)
   - на что меням (что он даёт взамен)
 - над его головой горит его имя жёлтым
 - не убиваем
 - ходит в очень небольшом радиусе (2м.) от первоначальной точки установки
 - передвигается редко (в 3-5 раз реже, текущих мобов)
 - когда обычный игрок кликает (любой кнопкой) по нему: 
   - форма с пиветствем/рассказом и полями для обмена
   - игрок кидает ему то, что "хочет" моб (то, что настроено)
   - получает взамен награду (то, что настроено)

**Comment by vladtcvs** [comment]
по идее выглядит как доработка торговцев

**Comment by alek13** [comment]
Неее... Торговцы:
 - спаунятся сами, этот устанавливается вручную
 - не имеют имени — надписи над головой
 - их много однотипных
 - меняют множество вещей, этот только одну
 - меняют именно на деньги, этот на что угодно
 - не имеют приветствия-рассказа "о наболевшем"
 - убиваемы, имеют лут, этот стоит где поставили и неубиваем
 - и главное — не имеют формы для настройки

**Comment by vladtcvs** [comment]
Ну вот я и говорю, что нужна доработка торговца, чтобы он делал вышеобозначенное

**Comment by vladtcvs** [comment]
Реализовано
