### ISSUE TITLE
Сброс скорости после сна

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#312]
**Описание ошибки:**

Если поспать в кровати с надетыми мифриловыми латами ~и кольцом воды~, то скорость персонажа упадет до обычной

**Как воспроизвести:**
Шаги воспроизведения на **_сервере_**:
_см. описание._

**Ожидаемое поведение:**
скорость осталась как в мифриловых сапогах

**Информация о клиенте:**
**Дополнительная нформация:**
Reported by Dlinnosheee

_прим. от @ptah-alexs :_
 - _если просто полежать, тоже скорость падает_
 - _от кольца не зависит_

**Comment by vladtcvs** [comment]
Спать в латах - дурной вкус)

**Comment by vladtcvs** [comment]
что конечно не отменяет бага

**Comment by vladtcvs** [comment]
Заодно надо рповерить что с зельями при сне происходит, возможно relates: #165

**Comment by ptah-alexs** [comment]
Тут запоминаются параметры при засыпании, потом восстанавливаются, поэтому действие зелья сохранится. Непонятно что будет с длительностью действия зелья, это зависит от того как там считается время окончания действия.

**Comment by vladtcvs** [comment]
Вообще, исправлять это все надо совместно с зельями - ввести список модификаторов у игрока, а не просто добавлять и убавлять параметры при срабатывании зелья или надевании лат.
