### ISSUE TITLE
Замедление после сна

### ISSUE THREAD

**Issue by ptah-alexs** [lord-server/lord#313]
Если лечь спать на кровать одетым в мифрилловые латы (шлем, кираса,поножи, сапоги), то после просыпания скорость движения становится обычной. Для ускорения приходится перенадеть сапоги.

**Информация о клиенте:**

 - OS: LInux
 - Client version: 5.3.0
 - Device: ПК

**Comment by alek13** [comment]
дубляж #312 , но спасибо :)
