### ISSUE TITLE
Админский магазин

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#314]
- при открытии пользователем с привилегией `"server"`, на форме:
   - появляется галочка "Админский (нескончаемый)"
 - при установленной голочке:
   - не отображаются "склад" и "выручка"
   - вместо них отображается счётчик покупки/продажи (для прив `"admin_pick"`)
   - обмен никак не взаимодействут со "скадом" и "выручкой":
     - товар на складе не уменьшается
     - обмен проходит даже если на складе нет товара, а только в "Цена" и "Предложение"
     - выручка не пополняется
 - при отсутствии галочки:
   - работает в штатном режиме

**Comment by VanicGame** [comment]
Хорошая идея.
