### ISSUE TITLE
Листва рябины не падает, когда рядом бревна маллорна

### ISSUE THREAD

**Issue by VanicGame** [lord-server/lord#315]
**Описание ошибки:**

Листва деревьев ребяны при отсутсвии стволов не падает, потому что рядом находится маллорн. Но маллорн является собсвенноручно поставленным, что не должно давать такого эффекта.

**Как воспроизвести:**

Не надо объяснений.

**Ожидаемое поведение:**

Листва упадёт

**Информация о клиенте:**

 - OS: [UNIX]
 - Client version: [5.4]
 - Device: [ПК]

**Дополнительная иформация:**

Раньше, некоторые стволы маллорна, которые я поставил сам, превратились в выросшие, т.е. те, которые падают как песок, когда рубишь. Тоже неприятно. Но я проверил, у меня все нормальные стволы.

**Comment by ssdaniel24** [comment]
Исправлено в #677.
