### ISSUE TITLE
Разная враждебность к игрокам разных рас

### ISSUE THREAD

**Issue by VanicGame** [lord-server/lord#317]
Описание:
К игроку определенной расы должны по-разному относится мобы разных рас. Например орков не должны быть орки.

Как это сделать:
Абсолютно всех мобов переключить на дружелюбных или нейтральных. Создать специальный алгоритм определения враждебности к игроку: Когда игрок попадает в поле зрения моба, определяем расу игрока; устанавливаем отношение к этому игроку так же, как и при ударе дружелюбных мобов, взамисимости от мобы и расы игрока. Таким образом, каждый игрок-орк, попадая в поле зрения моба-человека должен _якобы ударить_ (то же самое явление изменения отношения, только независимо от действий игрока) этого моба, а тот начать атаковать его.

**Comment by VanicGame** [comment]
Если непонятно написал, отпишите

**Comment by alek13** [comment]
сейчас так и есть.
@VanicGame сначала обсуди идею в какнале #обсуждение в [Discord](https://discord.gg/BabPfm6xtD), а потом уже сформированную идею закидываем сюда.

----
_А ещё лучше для начала сформированную идею закинуть на аппрув (вдруг есть противоречия, или нестыковки по коду) в канал #приёмная , а потом сюда уже_
