### ISSUE TITLE
Картины анигилируют блоки

### ISSUE THREAD

**Issue by VanicGame** [lord-server/lord#319]
**Описание ошибки:**

Если ты ставишь картину на место, где уже стоит блок, картина замещает этот блок.

**Как воспроизвести:**

Шаги воспроизведения на *[сервере]*:
Один из вариантов:
1. Ставим любой блок.
2. Ставим перед ним любой полублок, так, чтобы через этот полублок можно было увидеть блок.
3. Берём картину и наводимся курсором на блок через полублок (открытое пространство), ставим картину. Картина замещает собой полублок.

**Ожидаемое поведение:**

Картина не поставится, потому что блок уже занят.

**Информация о клиенте:**

 - OS: [UNIX]
 - Client version: [5.4, но наблюдалось и раньше]
 - Device: [ПК]

**Дополнительная информация:**

Теперь можно убирать тилкал:)

**Comment by ssdaniel24** [comment]
А также перила из lord_homedecor.

**Comment by alek13** [comment]
@ssdaniel24 , картины анигилируют **_любой_** блок, в том числе перила `lord_homedecor`.
Если имеется ввиду, что перила тоже анигилируют любой блок, то это похоже отдельный issue.
