### ISSUE TITLE
Больше безделушек

### ISSUE THREAD

**Issue by VanicGame** [lord-server/lord#320]
Цель данной идеи - добавить разнообразия на LORD.

Во-первых, это, как уже много раз упоминали, кулинария. Больше культур для выращивания, блюд для приготовления. У нас есть мясо и я думаю в Средеземье не питались только жаренными кусками. Различные отбивные, подливки, салаты. Кулинария должна быть не просто средством пополнения голода, чтобы не умереть, это должно быть настоящее искусство. Можно проработать алкоголь, чтобы были разные сорта пива, вина, сидра.

Во-вторых, строительные материалы. Различные каменные кладки, резьба по камню, колонны, материалы, плитка и прч. С деревом тоже можно поработать, не просто бревна-доски, а доски разной фактуры, струганные доски, паркет, резьба по дереву.

В-третьих, декор. Нужно больше всяких безделушек украшающих дома игроков, не типичные столы в каждом доме и стулья, которые уже надоели, а различная мебель. Несколько столов, одинаковых по материалу, но разных по конструкции смогут создать неповторимые уютные дома.

Доло уже кидал идею о кузнечном деле, но я бы хотел добавить, что можно делать разные мечи из одно и того же материала.

Обобщая, я хочу, чтобы мы не просто добавляли нечто новое, а брали уже существующее и делали его разнообразным.

**Comment by vladtcvs** [comment]
Кулинария должна что-то давать, помимо здоровья, чтобы это было осмысленно

**Comment by alek13** [comment]
Идея размытая, не сформированная, явно подвиснет мёртвым грузом в беклоге. Сначала обсуждаем в Discord'е с остальными, формируем со всеми концепт и потом уже формулируем чётко здесь
