### ISSUE TITLE
Растения не растут без игрока

### ISSUE THREAD

**Issue by Doloment** [lord-server/lord#321]
Посаженные на грядку растения не растут, если рядом нет игрока. В MTG же растения растут и без пристального наблюдения за ними

Всё дело в ABM, который использует наша версия lottfarming и farming, и который работает только, если в его радиусе есть игрок, в то время как в MTG используется Node Timers.

Related to #276

**Comment by vladtcvs** [comment]
аналогично с печками, дробилками, итд

**Comment by alek13** [comment]
Печки и пр. в default MTG находятся, я его почти закончил обновлять. Вот только отвлёкся на pvp

**Comment by alek13** [comment]
@lord-server/qa-engineer , это актуально ?

**Comment by blanka-kato** [comment]
Актуально

**Comment by blanka-kato** [comment]
Доверился меткам Refactorig и Update
