### ISSUE TITLE
Бутыльки наполняются только из котлов

### ISSUE THREAD

**Issue by Doloment** [lord-server/lord#323]
Бутыльки наполняются только из котлов, что надоедает при массовом производстве зелий.

Выдвигается на обсуждение, нужно ли это исправлять или нет.

**Comment by alek13** [comment]
Обсуждаем сначала в Discord.
Но LOTT-овский функционал мы пока стараемся по максимуму не трогать, пока не обновимся оттуда (хотя бы в последний раз).
Дальше либо мы стопаем обновления из LOTT и дальше пилим сами, но тогда мы теряем переводы, баг-фиксы, либо стараемся подобные правки делать вне кода LOTT-модов, а в наших модах-надстройках, которые находятся в отдельных папках, - чтобы LOTT-овские можно бы было у себя держать гитовыми сабмодулями.

Вообще на мой взгляд так и должно быть, т.к. это всё-таки зелья и их и правда должно сложно сделать. 
В любом случае пока закрываю, т.к.:
> Обсуждаем сначала в Discord.
