### ISSUE TITLE
Refactoring: `lottarmor`

### ISSUE THREAD

**Issue by vladtcvs** [lord-server/lord#339]
**Проблема:**

Код, отвечающий за броню, одежду, скины - ужасен и нечитаем.
~Одежда сломана.~ испр. в #390 

**Предложение:**

Привести его в порядок.

----

@alek13 :

- [x] del `player_textures` support
- [x] #976
- [x] #354
- [x] #971 
- [x] #972 
- [x] #973
- [x] #974
- [x] #975
- [x] #1011
- [x] #1012

**Comment by alek13** [comment]
Нужно обсудить на созвоне. Включу в повестку. Анонс созвона будет в Discord

**Comment by vladtcvs** [comment]
Одежда исправлена: #390
