### ISSUE TITLE
Зельеварение, или "Пьяная ведьма" 

### ISSUE THREAD

**Issue by Mikola314** [lord-server/lord#34]
Начинаем сюда коллекционировать баги по зельям.

**Comment by Mikola314** [comment]
- [ ] И первое у нас самая большая проблема, после смерти криво обнуляются эффекты от зелий и отравленных стрел. После смерти от яда, игрок дальше продолжает умирать уже после респа. Кучи трупов все видели. 
- [ ] "Паучье зелье" - используется для замедления и паралича. 
Баг: если выпить парализующее зелье на ходу, то персонаж продолжает двигаться в последнем заданном направлении без остановки. 
Есть косяк с всплывающей подсказкой для "сила +3" в книге Зельеварение https://github.com/weqqr/lord/issues/22

**Comment by Mikola314** [comment]
- [ ] "В перевод описания зелья энтов. Там написано "исцеляет, но мешает прыгать". Так вот, слово "исцеляет" нужно заменить на "ускоряет"."

**Comment by Mikola314** [comment]
- [ ] Можно выйти и зайти в игру - эффекты обнуляются.

**Comment by alek13** [comment]
закрываем, оставшееся вынесено в отдельные таски.
