### ISSUE TITLE
"Цветочки" или "Найди 100 косяков в Home Decor mod" 

### ISSUE THREAD

**Issue by Mikola314** [lord-server/lord#35]
- [x] В Home Decor mod в схемах Горшков с цветами и прочим используются дефолтные цветы, которых у на на серваке сроду не было, аналогично с кактусами....

**Comment by albel4** [comment]
Дефолтные цветы можно сорвать с верхней части некоторых хоббичьих домиков. Размножаться цветы могут только на земле Шира.

**Comment by Mikola314** [comment]
а они могут "размножаться" ?

**Comment by Mikola314** [comment]
- [ ] Поправить схемы новых факелов
