### ISSUE TITLE
"Головой об стену" или "Куда исчез узел при перезаходе игрока"

### ISSUE THREAD

**Issue by Mikola314** [lord-server/lord#36]
Очередной баг для гриферов. Раньше замечал, но не придавал значения. 
Ели использовать прохождение сквозь стены или баг с погружением вниз на чужой areas или запротекченной территории, потом выйти из игры и зайти обратно, в месте расположения "головы" персонажа узел удаляется совсем. 
Гриферы могут использовать для уничтожения протектов и прохождения внутрь построек под areas.

**Comment by albel4** [comment]
Возможно так таблички у нас и пропадают.

**Comment by Mikola314** [comment]
"Я кажется нашел причину исчезновения блоков при входе игрока. Вот здесь косяк:
minetest.register_on_joinplayer(function(player) 
local player_name = player:get_player_name() 
— перед добавлением игрока в таблицу поищем его там 
— вдруг был некорректный выход и он не удалился 
—for i,v in ipairs(players) do 
—if v == player_name then 
—table.remove(players, i) 
—end 
—end 
—table.insert(players, player_name) 
last_wielded[player_name] = player:get_wielded_item():get_name() — получим название предмета в руке 
local pos = player:getpos() 
local rounded_pos = {x=round(pos.x),y=round(pos.y)+1,z=round(pos.z)} 
local wielded_item = player:get_wielded_item():get_name() 
if wielded_item ~= "default:torch" and wielded_item ~= "light:streetlight" then 
— Neuberechnung des Lichts erzwingen 
— пересчет силы света 
minetest.set_node(rounded_pos,{type="node",name="air"}) 
end 
print("Регистрация "..player_name) 
player_positions[player_name] = {} 
player_positions[player_name]["x"] = rounded_pos.x; 
player_positions[player_name]["y"] = rounded_pos.y; 
player_positions[player_name]["z"] = rounded_pos.z; 
end)
Как решить пока не придумал и сегодня уже не придумаю. :) 
Если есть мысли ....
Точнее вот это условие:
if wielded_item ~= "default:torch" and wielded_item ~= "light:streetlight" then
minetest.set_node(rounded_pos,{type="node",name="air"})
end"
