### ISSUE TITLE
Отсутствует текстура default_tnt_bottom.png

### ISSUE THREAD

**Issue by Doloment** [lord-server/lord#372]
![image](https://user-images.githubusercontent.com/22934348/123082315-15e59280-d449-11eb-8051-c66e551029ce.png)
Мод lottmobs требует текстуру default_tnt_bottom.png для яйца призыва моба Half troll, а у нас такой нет в проекте.

Нужно либо добавить, либо обновить MtG и поменять название текстуры в коде.

**Comment by kevicky9** [comment]
<https://github.com/minetest/minetest_game/mods/tnt>
В новой версии Minetest_game `tnt` - отдельный мод

**Comment by Doloment** [comment]
> В новой версии Minetest_game `tnt` - отдельный мод
Вот и говорю, изменить в коде lottmobs название текстуры

**Comment by kevicky9** [comment]
Эту задачу можно сделать вместе с обновлением MTG

**Comment by Doloment** [comment]
Да, так и нужно.

**Comment by Doloment** [comment]
Не забыть #625
