### ISSUE TITLE
Лаги при движении на лошади

### ISSUE THREAD

**Issue by VanicGame** [lord-server/lord#378]
**Описание ошибки:**

При обследовании новых территорий на полигоне, ездя верхом на лошади, были замечены жуткие торможения. Едешь, тебя откидывает назад, едешь, снова откидывает, словно время перематывает. Поворот выполняется с задержкой, так же как и другие операции (слезть, залезть, убрать, поставить)

**Как воспроизвести:**

1. Найти несгенерированный кусок карты (большой)
2. Начать его объезжать на лошади
3. Наблюдать задержки
4. Слезать, залезать, ставить, доставать лошадь.

**Ожидаемое поведение:**

*без комментариев*

**Информация о клиенте:**

 - OS: [FreeBSD]
 - Client version: [5.4.1]
 - Device: [ПК]

**Дополнительная иформация:**

*нет*

**Comment by alek13** [comment]
1. Это издержки движка minetest, тут уж мы ничего сделать не можем.
2. Нужно понимать, что тестовый сервер крутиться на более слабом железе

**Comment by VanicGame** [comment]
Так сказал бы сразу... :)
