### ISSUE TITLE
Второй шанс не дает второгт шанаса

### ISSUE THREAD

**Issue by VanicGame** [lord-server/lord#380]
**Описание ошибки:**

*Вынесено из #377*

При использовании команды second_chance раса не меняется. Был хоббитом, решил поменять на человека, не сработало, на лошадях кататься не могу, сундуки заперты.

**Как воспроизвести:**

Шаги воспроизведения на полигоне:
1. Новый акк
2. Выбор расы - хоббит
3. Используем команду второго шанса
4. Выбираем человека
5. Пытаемся открыть роханский сундук или сесть на лошадь

**Ожидаемое поведение:**

*без комментариев*

**Информация о клиенте:**

 - OS: [FreeBSD]
 - Client version: [5.4.1]
 - Device: [ПК]

**Дополнительная Нформация:**

*нет*

**Comment by Doloment** [comment]
Не смог воспроизвести этот баг ‒ все сработало как надо. Действовал в точности по инструкции.

**Comment by VanicGame** [comment]
Хм. На полигоне?

**Comment by alek13** [comment]
закрыли, т.к. перестал воспроизводиться
