### ISSUE TITLE
Конь несет разлогиненого игрока

### ISSUE THREAD

**Issue by vladtcvs** [lord-server/lord#388]
**Описание ошибки:**
1. Едем на лошади
2. Разлогиниваемся
3. Конь продолжает вести себя так, как будто на нем игрок
4. Залогинившись по-новой, игрок может забрать своего коня, но не может сесть на него

Поведение полезное, т.к. коня не украсть при случайном разлогине, но это баг, а желаемый полезный эффект должен быть прописан явно

**Comment by alek13** [comment]
> а желаемый полезный эффект должен быть прописан явно
например ?
