### ISSUE TITLE
"Печатный станок" или "Баг ремонта инструментов"

### ISSUE THREAD

**Issue by Mikola314** [lord-server/lord#39]
Кладём в прилавок:
 - на "витрину" целый_инструмент
 - на склад товаров кладём ломаный_инструмент
 - в цену кидаем любой предмет (чего в кармане много)

![image](https://user-images.githubusercontent.com/1972329/51437128-b8aeeb00-1caa-11e9-8b2f-a543a13a19a9.png)

Начинаем у себя покупать. Получаем целый_инструмент. 
Стоимость "станка" = цене лицензии и материалов на сундук с замком.

Нужно полностью переписывать алгоритм покупки.

**Comment by alek13** [comment]
Не актуален.
Сейчас при попытке положить использованный (частично поломаный) предмет в инвентарь "Склад" магазина, выдаётся сообщение "Этот предмет должен быть новым", сам предмет возвращается в инвентарь игрока.
![image](https://user-images.githubusercontent.com/1972329/212551040-8768ed35-c87c-4fbe-b532-b7ae3226cf34.png)
