### ISSUE TITLE
Добавить возможность банить разлогиненного игрока

### ISSUE THREAD

**Issue by vladtcvs** [lord-server/lord#395]
Согласно @alek13, забанить грифера, который в данный момент разлогинен, невозможно и приходится поджидать, когда он залогинится

1. Добавить окно предупреждения, которое отобразится при логине
2. Аналогично бан игрока при логине

**Comment by ptah-alexs** [comment]
Может проще сделать список "ожидающих забан" при логине пользователя проверять его наличие в этом списке после чего получить его ip и автоматом забанить?
