### ISSUE TITLE
Ребалансировка оружия, брони и инструмента

### ISSUE THREAD

**Issue by albel4** [lord-server/lord#4]
Нужно убрать лишнее оружие и инструменты, ребалансировать урон, поправить “Эльфийский меч” (см. “Нарсил и призраки” #25 ) и Гномий топор. Добавить галворновую отвёртку. 
Стоит убрать дописки принадлежности расы в обуви (у хоббитов не было обуви, а у нас большая часть обуви на них записана).

**Comment by Mikola314** [comment]
Галворновая отвёртка добавлена. Подписи к обуви и большей части одежды исправили. №PR лень искать.

**Comment by alek13** [comment]
мысли разнесены по Epic'ам на RoadMap'е. Более не актуальна
