### ISSUE TITLE
Из 239: Рефакторинг создания материалов и оружия

### ISSUE THREAD

**Issue by Doloment** [lord-server/lord#400]
**Проблема:**

Несбалансированное PVP и переизбыток драгоценных материалов.

**Предложение:**

Усложнить производство металлов и компонентов для создания оружия при помощи введения дополнительных этапов в их изготовлении: отливка или ковка, вытачивание или формовка, а также сборка оружия и инструментов из конкретных частей.

**Существующие Моды:**

 - [Melterns](https://forum.minetest.net/viewtopic.php?f=9&t=19916), (для MT v5.0+), о-о-очень WIP мод, переделывать и доделывать надо чуть больше чем полностью

**Связанные задачи:**
 - #239 - откуда вынесено

**Comment by VanicGame** [comment]
Проблема долго вертевшаяся, решение вполне очевидное, только вот это усложняет саму добычу материалов, а не борется с их переизбытком на складах игроков. На первое время это усложнит игру лишь новичкам.
Важно распределить баланс между драгоценными материалами и обычными. Просто ограничить их добычу - этого мало.

Для ребаланса пвп, собственно, указанной проблемы, я бы предложил реализовать щиты, блокирующие урон либо частью от того, что получил (например, 70 % урона блокируется при зажатом шифте (привет МК)), либо блокировка всего урона с одной из сторон (просто аналог из МК)

Для ребаланса нападения - навыки. Мб уже говорили. В простейшем виде - итемы, накладывающие баффы на игрока при использовании с временем на перезарядку.

**Comment by Doloment** [comment]
ВАЖНО: во время реализации необходимо будет подредактировать луттэйблы с мобов и сундуков, чтобы оружие не так часто падало
