### ISSUE TITLE
Отвалился поиск в книгах крафта

### ISSUE THREAD

**Issue by Doloment** [lord-server/lord#418]
**Описание ошибки:**

Не работает поиск в книгах крафта *при вводе текста на русском языке*.
Не ищутся предметы, переведённые новым локализатором.

**Шаги воспроизведения**
1. Открываем книгу "Все рецепты"
2. Набираем в строке поиска "болт"
3. Ничего не найдено:
![image](https://user-images.githubusercontent.com/1972329/132104906-fcd5e032-49ea-4735-b143-ebac023609f0.png)

**Ожидаемое поведение:**
найдены болты:
![image](https://user-images.githubusercontent.com/1972329/132104946-383c9a41-5916-469f-80d1-a7a6b385098b.png)

**Информация о клиенте:**
 - OS: Windows 10
 - Client version: 5.4.1 (Но вообще пробовал на полигоне, там другая версия)
 - Device: ПК
 
**Дополнительная информация:**

Уточнение: вероятнее всего поиск не работает только для предметов из папки lord и (может быть) _minetest_game;

Отвалилось после https://github.com/lord-server/lord/commit/4566f902cdc6b48fddab01b986dbf7c288407f89 (мердж #367)

Связано с #419

**Comment by ptah-alexs** [comment]
У меня поиск на русском работает.

    OS: Linux Debian Sid
    Client version: 5.3.0
    Device: ПК

**Comment by alek13** [comment]
поправил описание, должно быть понятнее

**Comment by ptah-alexs** [comment]
С одной стороны есть https://github.com/minetest/minetest/pull/9733 но minetest.get_translation(lang_code, string) падает с любым lang_code: attempt to call field 'get_translation' (a nil value)

**Comment by ptah-alexs** [comment]
Кроме того, в ванильном minetest_game поиск по русски тоже не работает.
