### ISSUE TITLE
Отвалился поиск в меню /list

### ISSUE THREAD

**Issue by Doloment** [lord-server/lord#419]
**Описание ошибки:**

Не работает поиск в меню `/list` *при вводе текста на русском языке*

**Ожидаемое поведение:**

Нормальное функционирование поиска в меню `/list`

**Информация о клиенте:**

 - OS: Windows 10
 - Client version: 5.4.1 (Но вообще пробовал на полигоне, там другая версия)
 - Device: ПК
 
**Дополнительная информация:**

Уточнение: вероятнее всего поиск не работает только для предметов из папки lord и (может быть) _minetest_game;

Отвалилось после https://github.com/lord-server/lord/commit/4566f902cdc6b48fddab01b986dbf7c288407f89 (мердж #367)

Не критично, в отличии от #418

Связано с #418

**Comment by Doloment** [comment]
Перепроверить на наличие бага

**Comment by alek13** [comment]
**Шаги воспроизведения:**
1. комада `/list`
2. в поисковой строке вводим `дробилка`

не находит
