### ISSUE TITLE
дополнение к ЖД-моду

### ISSUE THREAD

**Issue by Mikola314** [lord-server/lord#43]
Есть мод Железные Дороги (ЖД) https://forum.minetest.net/viewtopic.php?t=2451
Есть мод Mesecons - мод https://forum.minetest.net/viewtopic.php?t=2451
 
Если на сервер НЕ установлен Mesecons, ЖД-мод работает автономно. Есть Mese-рельсы для ускорения. Когда нет Mesecons, тележка просто ускоряется при попадании в этот узел (Mese-рельсы).
Если на сервер установлен Mesecons, ЖД-мод работает совместно с Mesecons.. Когда есть Mesecons, тележка ускоряется при попадании на Mese-рельсы Только когда есть «питание» этого участка от Mesecons-источников.

Мы не можем установить Mesecons на наш сервер – он не впишется в стиль мира. Но и просто Mese-рельсы меня не устраивают. Нереалистично. Гномы конечно тоже применяют немного магии, но не в такой степени. 

Вот моё предложение:
Мы устанавливаем ЖД-мод без Mesecons. Но делаем дополнение к ЖД-моду.
Маленькая отсылка: у нас на сервере есть мод bones. Там есть такой объект как «Скелет». Это составной объект: туловище и голова. Игрок устанавливает скелет на пол. Устанавливает нижнюю часть. Автоматически устанавливается вторая часть – голова. При попытке сломать голову – игрок ничего не получает. При попытке сломать нижнюю часть – получает Скелет. 
Я предлагаю использовать этот алгоритм для модификации ЖД.
Как это должен видеть игрок:
1) Объекты: объекты ЖД-мода + «Шестерня» + «Паровой механизм»
2) Крафт:
Шестерня

(пусто) | Слиток стали | (пусто)
------------ | ------------- | -------------
Слиток стали | (пусто) | Слиток стали 
(пусто) | Слиток стали | (пусто)

Паровой механизм

Слиток стали | Палочка из любого дерева | Слиток стали
------------ | ------------- | -------------
Шестерня | Полный котёл с водой | Человеческий факел 
Слиток стали | Блок угля | Слиток стали

Убрать крафт Mese-рельс

- Зачем нужна Шестерня? 
- Её можно будет использовать при добавлении Пилорамы из другого мода (мод ещё не переделали).

3) Игровой процесс:
Игрок делает ЖД дороги, делает тележку, делает Паровой механизм.
Игрок укладывает обычные рельсы. С некоторой периодичностью выкапывает блок ниже узлов с рельсами и ставит в углубление Паровой механизм. Сразу после установки Парового механизма, над ним устанавливается Mese-рельсы. Дальше игрок может пользоваться Тележкой как и при автономно работающем ЖД-моде. Тележка будет ускоряться на Mese-рельсе «над Паровым механизмом». Если игрок попытается разрушить Mese-рельсы – ничего не получит (желательно сделать возвращение Mese-рельс на место). Если игрок попытается разрушить Паровой механизм, то получит в инвентарь Паровой механизм. Паровой механизм и Mese-рельсы убираются (полная аналогия с алгоритмом Скелета).

- А паровой двигатель топливо будет кушать?
- Нет. А то обслуживать заколебутся....

4) 3D-модели:
Модель шестерни не нужна. Её не нужно устанавливать в мире как отдельный 3D-объект. 
Моделька Парового механизма – стандартный куб.

5) Текстуры:
Текстуру шестерни можно найти в чужом моде или нарисовать самому, если не лень.
Текстура Парового механизма в виде коробки с трубками и торчащими шестернями.
Перекрасить текстуру Mese-рельс: простые рельсы и 2 шестерёнки между рельсами.

**Comment by Mikola314** [comment]
единственный косяк, который пришёл в голову: какой именно узел Mese-рельсе быдет выгружаться? Там есть 2 разных направления + развилка + углы.

**Comment by Mikola314** [comment]
Пробую сам сделать.

**Comment by Mikola314** [comment]
- [ ] убрать куски, связанные с mesecon-mod
- [ ] перенести куски дефолтных рельс в carts-mod

**Comment by Mikola314** [comment]
"Заморожено" из-за проблемы с приклеиванием скина и ника игрока к тележке во время поездки.

**Comment by weqqr** [comment]
работает в 0.4.14
