### ISSUE TITLE
Ingot textures #408 расположили не в той папке

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#432]
Ingot textures #408 расположили не в той папке.
Папки из MTG должны полностью совпадать с оригиналом вплоть до байта.
Наши текстуры, которые мы переделываем/заменяем должны находиться в `mods/lord/_overwrites/MTG/.../textures`, например в `mods/lord/_overwrites/MTG/default/textures`
@VanicGame

**Comment by VanicGame** [comment]
ну емое
