### ISSUE TITLE
Нет плит и ступенек из алмазного блока

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#437]
**Описание ошибки:**

Нет ступенек из алмазного блока

![image](https://user-images.githubusercontent.com/1972329/133163529-309f2fc3-2fde-434a-8d92-e63b81f531ab.png)

![image](https://user-images.githubusercontent.com/1972329/133163713-bd04a1e8-6bf4-4621-8904-4b1d53f3e976.png)

**Comment by weqqr** [comment]
5557a1c6b2c09b6fc03f2e980e6b921532d4df2c
