### ISSUE TITLE
Полублоки (плитки блоков) тратятся в creative режиме

### ISSUE THREAD

**Issue by VanicGame** [lord-server/lord#446]
**Описание ошибки:**

При игре в creative полублоки тратятся, тогда как обычные блоки (целые) нет.

**Как воспроизвести:**

Шаги воспроизведения в локальной игре:
1. Включаем креатив
2. Берём в руку полублок
3. Ставим полублок (наблюдаем, что кол-во не уменьшилось)
4. Ставим полублок на этот полублок или в любую другую сторону, но обязательно, чтобы курсор был на поставленном ранее.
5. Наблюдаем: Полублок поставился так же, как и прошлый, но уже кол-во их уменьшилось.

**Ожидаемое поведение:**

Плитка тратится не будет

**Информация о клиенте:**

 - OS: [FreeBSD]
 - Client version: [5.4.1]
 - Device: [ПК]

**Дополнительная информация:**

Это не имеет высокий приоритет, т.к. криатива на сервере нет (вроде), но в локальной игре такое тормозит стройку.

**Comment by ssdaniel24** [comment]
Баг minetest_game, более не наблюдается.
