### ISSUE TITLE
Гондорские сундуки в Минас-Тирит

### ISSUE THREAD

**Issue by VanicGame** [lord-server/lord#447]
**Описание ошибки:**

Найдено @vladtcvs
![изображение](https://user-images.githubusercontent.com/82447582/134809027-65af3423-d8f0-42c7-ba0a-6385f8339b29.png)

**Как воспроизвести:**

Шаги воспроизведения на *сервере*:

Открыть нужный сундук в Минас Тирите (но я не уверен)

**Ожидаемое поведение:**

Увидеть внутренности сундука

**Информация о клиенте:**

(без понятия)

**Дополнительная информация:**

За подробной информацией обращаться к @vladtcvs

**Comment by vladtcvs** [comment]
проявляется не у всех сундуков

**Comment by alek13** [comment]
если нет координат, и не ясно как воспроизвести, то я закрою.
@vladtcvs сможешь найти где это ?

**Comment by vladtcvs** [comment]
Я больше не встречал таких

**Comment by vladtcvs** [comment]
Я больше не встречал таких
