### ISSUE TITLE
"Я тебя из под земли достану!" или учимся на агронома. 

### ISSUE THREAD

**Issue by Mikola314** [lord-server/lord#46]
Предлагаю немного поправить сбор урожая и то, что нужно посадить для пшеницы, ячменя, кукурузы и картошки.

Пшеница. В наличии есть "Пшеница" (текстура  старых "Семена пшеницы"). Сажаем "Пшеницу". Дальше рост как обычно. Собираем "Сноп пшеницы" (вероятность как у старой "Пшеница", лут старых "Семена пшеницы" убираем). Кладём сноп на поле крафта и получаем "Пшеница" 6 шт. 
Можем сажать их. Можем положить на поле крафта 4 шт "Пшеница" и получить муку..... 

Ячмень. Принцип аналогичный Пшенице. Не забываем подправить схемы с конечным продуктом.

Кукуруза. Аналогично.

Картошка. Тут всё просто. Увеличить лут картофелин в 2 раза, убрать лут семян. Сажать картофелины. Или оставить "семена" - "Половина картофелины" (перерисовать текстурку),

Собираюсь попробовать сам. Добавлять и удалять не придётся. Просто рокировка текстур и объектов в схемах.

**Comment by albel4** [comment]
У меня ещё была задумка поменять текстуру кукурузы, на более внятную. Но остановило то, что придется кодить, а текущая текстура в общем-то работает. 
Насчет семян согласен. Картошку семенами не сажают, хотя они здесь и похожи на "глазкИ". :)
Да и зерно добывать из пшеницы или ячменя методом обмолота как-то реальнее.
Кстати и у хлопка есть текстурка поинтереснее.

**Comment by Mikola314** [comment]
Я только за текстурки получше. Narrnika спрашивает: "Репа должна быть такого цвета? Она обычно белая/жёлтая ) "

**Comment by albel4** [comment]
Это турнепс :)

**Comment by Mikola314** [comment]
"Это турнепс :) А репа, да, желтая."  - перерисовать?

**Comment by albel4** [comment]
Можно.

**Comment by TheEagleEye** [comment]
Может соберете список текстурок и переклепаете одним махом?

**Comment by Mikola314** [comment]
"Может соберете список текстурок и переклепаете одним махом?" я и так этими правками занялся. Список замен составил, сегодня постараюсь перекопать код.

**Comment by Mikola314** [comment]
Сделано

**Comment by vladtcvs** [comment]
некоторые сажают картошку из семян. Урожай на 2-й год происходит, но пишут, что намного лучше

**Comment by Mikola314** [comment]
vladtcvs, предлагаешь кроме половинок ещё и семена добавить с увеличенным временем роста первых уровней кустика?

**Comment by vladtcvs** [comment]
можно попробовать. А сами семена ядовитыми сделать)
