### ISSUE TITLE
Деревянный топор аналогичен руке

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#461]
Добавить деревянному топору немного скорости

**Comment by kevicky9** [comment]
У руки `full_punch_interval` равен 0.9, а у деревянного топора - 1.0. Топор должен быть быстрее руки?

**Comment by VanicGame** [comment]
вообще, как бы нет. Ты будешь быстрее наносить удары рукой, чем чем-то, что в ней лежит. У руки вес меньше, чем у руки и топора. Тут должна быть разница в скорости добычи
