### ISSUE TITLE
Куда исчезает пшеница?

### ISSUE THREAD

**Issue by VanicGame** [lord-server/lord#467]
**Описание ошибки:**

Крафт блока сена состоит из 9ти пшеницы.
Тогда как пшеницы из блока сена получается всего **3!**

**Как воспроизвести:**

Шаги воспроизведения на *везде*:
1. Открываем инвентарь
2. Из 9 пшениц крафтим блок сена.
3. Забираем блок.
4. Кладем в сетку крафта.
5. Забираем 3 пшеницы.

**Ожидаемое поведение:**

Из одного блока девять пшениц.

**Информация о клиенте:**
_Думаю, нет смысла указывать_

 - OS: [<Android|Windows|Linux|...>]
 - Client version: [<5.0|5.1|...>]
 - Device: [<ПК|iPhone6|Android-Телефон|Android-планшет|...]

**Дополнительная нформация:**
нет

**Comment by Doloment** [comment]
Несостоятельно: при крафте блока получается 3 штуки. Закрыто.
