### ISSUE TITLE
Любой предмет можно вставить в слот персонажа

### ISSUE THREAD

**Issue by ghost** [lord-server/lord#47]
![image](https://user-images.githubusercontent.com/1972329/53688854-7a055980-3d5b-11e9-9021-758d64b1c719.png)

Фича или .. ?

**Comment by Mikola314** [comment]
скорее баг. Толку от этого не наблюдается. Кстати, иконки под этими полями нужно подрихтовать, Рисунок персонажа сместить.

**Comment by Doloment** [comment]
Уже нету этого бага
Можно закрывать

**Comment by Mikola314** [comment]
Баг вылечен не полностью. Сейчас на локалке с последней версией уложил камни во все слоты одежды, кроме брони и щита.

**Comment by Doloment** [comment]
Перестал появляться, на этот раз окончательно. Вероятно, после #390
