### ISSUE TITLE
Возможность положить посторонний предмет в выдачу товара менялы

### ISSUE THREAD

**Issue by vladtcvs** [lord-server/lord#481]
**Описание ошибки:**

Есть возможность положить свой предмет в инвентарь выдачи товара менялы

**Как воспроизвести:**

Шаги воспроизведения:
1. Заходим в менялу
2. Кладем указанную цену в инвентарь оплаты
3. Берем товар из инвентаря выдачи товара и кладем себе в инвентарь в ячейку, где уже что-то лежит
4. Это что-то оказывается в процессе переноса
5. Кладем его в ячейку выдачи товара
6. Это ошибка

**Ожидаемое поведение:**

Нет возможности положить переносимые предметы в инвентарь выдачи товара

**Comment by vladtcvs** [comment]
Предполагаемая природа бага:

Инвентари в MT весьма контринтуитивно устроены.
1) На самом деле ты берешь что то из инвентаря не в тот момент, когда ты визуально это взял, а когда взятое положил в какую либо другую ячейку. И именно в этот момент производится проверка допустимости таокго действия. 
2) В коде MT где-то дополнительно хранятся ссылки на инвентари, и поэтому нет возможности просто задать содержимое инвентаря - при этом инвентарь на самом деле заменится на новый. Есть возможность только добавлять и убирать из инвентаря.
3) Отсутствие инвентарья для переносимого в данный момент предмета приводит к тому, что ты не сперва взял предмет, переместил его в инвентарь переноса, а затем положил в целевой инвентарь, а сразу переместил из исходного в целевой.

И если я не ошибаюсь, то когда ты кладешь что-то в ячейку, где уже что-то лежит, MT использует исходный инвентарь для хранения того, что было в целевой ячейке до того, как ты туда положил переносимое. Игнорируя при этом запреты на помещение чего-либо в исходный инвентарь, если таковые есть. Это и приводит к багу

**Comment by VanicGame** [comment]
Дополнение:

![изображение](https://user-images.githubusercontent.com/82447582/140620036-801505cc-3ea6-4be0-8853-0c3c1ea1e39d.png)
![изображение](https://user-images.githubusercontent.com/82447582/140620042-6a65ae19-1763-4570-9c48-f6d67bead94a.png)
![изображение](https://user-images.githubusercontent.com/82447582/140620047-7cecb303-6159-4540-b297-f7880411d218.png)
![изображение](https://user-images.githubusercontent.com/82447582/140620052-e9efcaf0-f3e6-4d7f-97fa-38d16ccb4301.png)
![изображение](https://user-images.githubusercontent.com/82447582/140620054-73e9a018-87e3-47be-9cc7-69b052e48d25.png)
![изображение](https://user-images.githubusercontent.com/82447582/140620074-46c68d4d-68f9-41e7-8462-345bd062f428.png)
![изображение](https://user-images.githubusercontent.com/82447582/140620063-456e5cf7-46d1-4684-a8f1-324e33f7d0a0.png)

Прим.: исчезновение работает только с теми предметами, что **должны** лежать в этом слоте, т.е. с тем, что меняла продаёт.

Прим.: Возможны и другие разновидности бага с исчезновением, которые могут быть вызваны хаотичными действиями двух и более игроков, тогрующих с менялой. Большинство багов должно быть исправлено, если будет запрет на возможность положить в менялу что-то своё.

**Comment by ssdaniel24** [comment]
Исправлено в 4c7c56e5dfa6264808fb678815663679bc7feec6.
