### ISSUE TITLE
Краш при поиске в книге крафта

### ISSUE THREAD

**Issue by zhelnin-a** [lord-server/lord#497]
**Происходит отключение всех клиентов:**

Происходит отключение всех активных клиентов(очевидно краш и перезапуск  сервера) при поиске на английской раскладке в книге крафта с последующим вываливание клиентам ошибки сервера. 
Нужно проверить все вариации. Возможно связано с нажатием кнопки _Enter_.

Ошибка, вываливающаяся в логах клиента игры:
```
2021-12-07 22:17:20: ERROR[Main]: Access denied. Reason: This server has experienced an internal error. You will now be disconnected.`
```

**Как воспроизвести:**

Шаги воспроизведения на _сервере_:
1. Открываем инвентарь
2. Берём книгу _"Основы крафта"_
3. В поиске вбиваем слово _холст_ на английской раскладке
4. Нажимаем _Enter_
5. Всех пользователей выбрасывает с сервера с ошибкой

**Информация о клиенте:**

 - OS: [Linux]
 - Client version:5.4.1
 - Device: [ПК]

**Дополнительная информация:**
Об ошибке сообщил пользователь Throrin
Оригинальное сообщение в чате игры(discord/#на-сервере):

> 2021-12-06 22:42:05: <Throrin> Если в поиске в книге основы кравта вдить слово холст на английской раскладке всех выкидывает с сервера.

**Comment by weqqr** [comment]
Исправлено в #496
