### ISSUE TITLE
Падение сервера при вводе /xban_gui

### ISSUE THREAD

**Issue by zhelnin-a** [lord-server/lord#504]
**Описание ошибки:**

Падение сервера при вводе команды `/xban_gui`, которая отображается любому пользователю при использовании команды `/help all`

**Как воспроизвести:**

Шаги воспроизведения на *сервере*:
1. Открываем чат
2. /xban_gui
3. Падение и презапуск сервера ~5 мин.

**Ожидаемое поведение:**

Сообщение о том, что нет привилегий для использования данной команды

**Информация о клиенте:**

 - OS:Linux
 - Client version: 5.4.1
 - Device: ПК

**Дополнительная информация:**

Разумнее вообще не выдавать `/xban_gui` на выводе команды `/help all`

**Comment by VanicGame** [comment]
В качестве меры команду отключили, дальнейшие исправления уже касаются lord_ext. Issue closed.
