### ISSUE TITLE
Нескончаемые прилавки некорректно проверяют оплату

### ISSUE THREAD

**Issue by weqqr** [lord-server/lord#512]
**Описание ошибки:**

При неполной оплате прилавок чинит инструмент.

**Как воспроизвести:**

Починить кирку у Sachiel, положив в качестве оплаты только кирку.

**Comment by vladtcvs** [comment]
происходит только на нескончаемых прилавках?

**Comment by weqqr** [comment]
Я не тщательно тестировал, но да.
