### ISSUE TITLE
Полупрозрачный фон ников на 5.4.1

### ISSUE THREAD

**Issue by vladtcvs** [lord-server/lord#523]
![image](https://user-images.githubusercontent.com/3390973/148683623-1f9605c5-8c72-4ba2-b74e-616b1ca915ea.png)

**Comment by vladtcvs** [comment]
Причем проблема есть и когда сервер 5.0, а клиент 5.4

**Comment by alek13** [comment]
а в чём баг то ?

**Comment by alek13** [comment]
так и было задумано, закрываем.
если нужно будет, после обсуждения в Discord, создадим тикет обычный
