### ISSUE TITLE
Окно редактирования привата не закрывается по Esc.

### ISSUE THREAD

**Issue by vladtcvs** [lord-server/lord#524]
**Описание ошибки:**

Окно редактирования привата не закрывается по Esc.

**Как воспроизвести:**

1. Установить знак привата
2. Кликнуть правой кнопкой
3. Нажать Esc
4. Окно моргнет и останется открытым

Закрыть же можно только нажав мышью по кнопке закрыть

**Ожидаемое поведение:**

Окно закроется.

**Актуальность проблемы**

Как минимум я регулярно случайно задеваю знак привата, когда лезу, например, в стоящий рядом сундук или что-еще. И хочется иметь возможность быстро закрыть если случайно открыл

**Comment by zhelnin-a** [comment]
На полигоне есть проблема. Но если тестить локально, то все нормально, хммм.
