### ISSUE TITLE
Создание книги-верстака для мобильной версии

### ISSUE THREAD

**Issue by Doloment** [lord-server/lord#53]
В minetest обычно начинают играть с мобильныз устройств. В моб. версии не оптимизирован нормальный крафт предметов (невозможно раскладывать предметы из стака в сетке крафта). Требуется создать книгу с мобильным крафтом (по нажатию кнопки), либо выставить все предметы и их рецепты крафта в окне инвентаря, соответственно, убрав все книги крафта. Есть вариант сделать в инвентаре такой архив, пополняемый САМИМИ книгами крафта. Эту проблему надо устранять (сам не кодер, сделать не могу).

**Comment by Mikola314** [comment]
Лично я против поддержки мобильной версии... Слишком всё криво в этих версиях. У одного карты нетЬ.. У другого "а что такое координаты?" .. "у меня лагает". "i ne mogy pisat na russkom(..."
Игра не расчитана изначально на эти сенсорные калькуляторы.. Ну и + какой контингент обычно играет с этих калькуляторов.. 
+ с игровой точки зрения - это сделает ещё на шаг ленивее игроков - клацнул кнопочку - материалы разложились... "Красота!"..
я понимаю, что не все могут себе позволить ПК или форточно/пингвинячий ноут или планшет с 10" ... Но и под все калькуляторные клиенты не подстроиться...
