### ISSUE TITLE
Несоответствие экипировки мобов и дропа с них

### ISSUE THREAD

**Issue by weqqr** [lord-server/lord#54]
Например, из эльфа с эльфийским мечом падает меч серебряный
`<WArYag> блин. почему из эльфа в галворне падают доски?`

**Comment by Mikola314** [comment]
Хорошее замечание, постараемся исправить.

**Comment by Mikola314** [comment]
Хорошее замечание, постараемся исправить.
(не туды ткнул..)

**Comment by vladtcvs** [comment]
А не станет ли мифрил и галворн слишком распространенными?

**Comment by Mikola314** [comment]
vladtcvs станет, кроме лута нужно разбираться с спавном мобов - это сложнее.

**Comment by alek13** [comment]
отложено до формирования проекта по перебалансировке мобов
