### ISSUE TITLE
Проблема с текстом на табличке `signs:sign_post`

### ISSUE THREAD

**Issue by zhelnin-a** [lord-server/lord#543]
**Описание ошибки:**

Проблема с прозрачностью текста у табличек `signs:sign_post`

![screenshot_20220213_111837](https://user-images.githubusercontent.com/17987998/153750390-65dc512e-e45a-4348-9603-1133211aa9bc.png)

**Как воспроизвести:**

Шаги воспроизведения на *полигоне*:
1. Установить табличку `signs:sign_post' и написать текст
2. Через какое-то время(думаю рестарт сервера) смотрим снова на табличку
3. Текст на табличке меняем свою прозрачность при изменении угла обзора
4. Переустанавливаем табличку и пишем текст. Текст отображается снова нормально
5. Через какое-то время история с текстом повторяется.

**Информация о клиенте:**

 - OS: [Linux]
 - Client version: [5.4.1]
 - Device: [ПК]

**Comment by alek13** [comment]
Дубль https://github.com/lord-server/lord/issues/459
Был пофикшен.
На всякий проверил ещё раз:
![image](https://github.com/lord-server/lord/assets/1972329/7a9b2208-c329-40c2-9f65-d0391fe5a2dd)
