### ISSUE TITLE
Не достать цветы для горшков

### ISSUE THREAD

**Issue by vladtcvs** [lord-server/lord#546]
Горшок с цветком можно сделать из
1. герани
2. одуванчика белого
3. одуванчика желтого
4. розы
5. тюльпана
6. фиалки

Эти цветы определены в MTG/flowers. И они генерятся только на `default:dirt_with_grass`, которой у нас не встречается

А цветы, которые у нас растут, в горшки не посадить

**Comment by vladtcvs** [comment]
Уточнение: если у тебя уже есть цветы ты их можешь размножить. Но достать в природе - я так и не нашел где

**Comment by Doloment** [comment]
Природе не генерятся, а достать их можно при разборе домиков хоббитов

**Comment by alek13** [comment]
Fixed in #1083
