### ISSUE TITLE
Использование мобов как транспорт

### ISSUE THREAD

**Issue by googolgl** [lord-server/lord#55]
Можно попробовать связать использование мобов как транспорта с расой игрока-наездника. Для каждой расы свой список транспорта. 
- [x] **Орки** - могут на варгах ~и назгулах~
- [x] **Люди** - на конях ~, орлах, пони и в паровозах (машинист)~
- [x] **Эльфы** - на конях ~и орлах~
- [x] **Хоббиты** - на пони ~и орлах~
- [x] **Гномы** - на пони, кабанах ~, орлах, и в паровозах (машинист)~

- [x] Добавить "Кольцо Зверя" - возможность оседлать любое доступное существо ( ввод в игру: #287 )

**Comment by googolgl** [comment]
Возможно имеет смысл добавить "Кольцо Зверя" - для возможности приручать не связаных с рассой мобов.

**Comment by Mikola314** [comment]
googolgl, дельная мысль.

**Comment by Mikola314** [comment]
На данный момент добавлены варги и кабаны.

**Comment by vladtcvs** [comment]
Орлы?

**Comment by Mikola314** [comment]
vladtcvs, сделать модельку. по аналогии с драконами и птицами. Добавить возможность сидеть на них и летать. 
"Эльфы - на конях и орлах
 Хоббиты - на пони и орлах"

**Comment by vladtcvs** [comment]
Не, хоббиты только в когтях)

**Comment by vladtcvs** [comment]
как и гномы

**Comment by Mikola314** [comment]
http://www.picshare.ru/uploads/130307/t8a7ddvRc1.gif )

**Comment by vladtcvs** [comment]
ну так Гэндальф на орле. Но он майяр, а такой расы у нас все равно нет

**Comment by vladtcvs** [comment]
Хоббит:

"Тогда Гэндальф забрался на самую верхушку. Из его посоха вырвалось невиданное ослепительное сверканТогда Гэндальф забрался на самую верхушку. Из его посоха вырвалось невиданное ослепительное сверкание. Волшебник приготовился спрыгнуть с высоты прямо на копья гоблинов. Тут бы ему и конец, но зато он, наверное, убил бы немало врагов, свалившись им на головы. Но он не успел прыгнуть."

В этот миг с неба на него упал Повелитель орлов, схватил в когти — и взмыл ввысь.ие. Волшебник приготовился спрыгнуть с высоты прямо на копья гоблинов. Тут бы ему и конец, но зато он, наверное, убил бы немало врагов, свалившись им на головы. Но он не успел прыгнуть.

В этот миг с неба на него упал Повелитель орлов, схватил в когти — и взмыл ввысь.

**Comment by vladtcvs** [comment]
В общем, орлы - птицы гордые. И управлять ими, как пони, нельзя

**Comment by vladtcvs** [comment]
![eagle](https://user-images.githubusercontent.com/3390973/30254085-b4bda7b6-969b-11e7-8cce-ffe6fc737dfe.jpeg)

**Comment by Mikola314** [comment]
На данный момент выполнено:
Орки - на варгах
Люди - на конях
Эльфы - на конях
Хоббиты - на пони
Гномы - на пони, кабанах
Добавить "Кольцо Зверя" - возможность оседлать любое доступное существо.
Кольцо Зверя не введено в игровой процесс из-за неопределённости со сложностью и рецептом сборки.

**Comment by Mikola314** [comment]
При тестировании на полигоне в режиме креатив пары орка и варга непонятным образом получил игнор от всех транспортных мобов - нет никаких сообщений о невозможности поездки, поездка не начинается, кольцо зверя не помогает. "Второй шанс" (смена расы) не помог.
Второй персонаж-орк спокойно смог взаимодействовать с мобами.

**Comment by alek13** [comment]
тестил в обычном режиме, всё норм.
