### ISSUE TITLE
Ошибка регистрации псевдонима `default:sign_wall -> default:sign_wall_wood`

### ISSUE THREAD

**Issue by zhelnin-a** [lord-server/lord#550]
**Описание ошибки:**

`WARNING[Main]: Not registering alias, item with same name is already defined: default:sign_wall -> default:sign_wall_wood`

**Информация о клиенте:**

 - OS: Linux
 - Client version: 5.4.1
 - Device: ПК

**Дополнительная информация:**

```
mods/lord/_overwrites/MTG/default/init.lua
53: minetest.register_alias("sign_wall", "default:sign_wall")
89: minetest.register_alias("default:sign_wall", "default:sign_wall_wood")
90: minetest.register_alias("default:sign_wall_wood", "default:sign_wall")

```

**Comment by weqqr** [comment]
#563
