### ISSUE TITLE
Дроп еды с мобов и разнообразие еды

### ISSUE THREAD

**Issue by Doloment** [lord-server/lord#57]
С мобов падает только один вид мяса. Требуется сделать чтобы с каждого моба падало разное. Также добавить другую еду помимо салатиков, фруктов, всвязи с введением моркови и рыб.

~=позже

Список еды для добавления:

- [x] Сырая рыба 

- [x] Сырая конина~

- [x] Сырая курица

- [x] Cырая крольчатина~

- [x] Жареная рыба (ранее в этих скобках была брехня)

- [x] Жареная конина~

- [x] Жареная курица

- [x] Жареная крольчатина~

- [x] Сырое яйцо

- [x] Яичница

- [x] Крекер

- [x] Лембас (без крафта и дропа)

- [x] Дроп мяса

- [x] Вывести отдельно "мясо орка"(Гнилое Мясо)

- [x] Дроп Гнилого Мяса

- [x] Тесто

- [ ] Механика выпадения яйца

- [x] Крафт жаренного мяса

**Comment by Mikola314** [comment]
В чём отличие от https://github.com/lord-server/lord/issues/54 ?

**Comment by Doloment** [comment]
Шоколад добавлять будем?

**Comment by Mikola314** [comment]
Doloment, не вижу смысла.

**Comment by Doloment** [comment]
Список еды для добавления:

- [ ] Сырая рыба 

- [ ] Сырая конина

- [ ] Сырая курица

- [ ] Cырая крольчатина

- [ ] Жареная рыба (+1 голод, -1 здоровья)

- [ ] Жареная конина

- [ ] Жареная курица

- [ ] Жареная крольчатина

- [ ] Сырое яйцо

- [ ] Яичница

- [ ] Печенье

- [ ] Вывести отдельно "мясо орка"(Гнилое Мясо)

**Comment by Mikola314** [comment]
Doloment , поддерживаю

**Comment by Doloment** [comment]
Предлагайте еще еды
