### ISSUE TITLE
Lamps не lamp'сит

### ISSUE THREAD

**Issue by VanicGame** [lord-server/lord#575]
**Описание ошибки:**

Может мне кажется, но у ламп из мода lamps очень маленький параметр света...

**Как воспроизвести:**

В темное место поставить лампу

**Ожидаемое поведение:**

Света будет больше

**Информация о клиенте:**

 - OS: [<Android|Windows|Linux|...>]
 - Client version: [<5.0|5.1|...>]
 - Device: [<ПК|iPhone6|Android-Телефон|Android-планшет|...]

**Дополнительная нформация:**

Надо поправить бы...

**Comment by alek13** [comment]
так и должно быть:
1. свет проходит ещё и через стекло, в отличии от факела
2. они колоритно смотрятся в соответствующих постройках/местах именно с таким освещением
