### ISSUE TITLE
Перенести hud_modpack в папку lord

### ISSUE THREAD

**Issue by Doloment** [lord-server/lord#582]
эти моды тоже надо бы на авто-апдейт перевести
----
Doloment. — Today at 7:33 PM
:0 а они ж в стороннем моде, который перепахан 100500 раз, причем мной
да и обновлять их нет особого смысла, мне кажется 
Doloment. — Сегодня, в 23:35
потому что там примерно 50% моего кода в каком-то из модов
так еще я думаю они не особо обновились за это время
Alek — Сегодня, в 23:36
хм...
Doloment. — Сегодня, в 23:36
Я бы просто в lord папку перенес

**Comment by alek13** [comment]
Done by #1529
