### ISSUE TITLE
Мумия или нетленный труп.

### ISSUE THREAD

**Issue by Mikola314** [lord-server/lord#59]
Есть предложение, сделать самоуничтожение пустых Ничейных трупов по таймеру. Таймер 2 реал. часа (игровые сутки).

**Comment by Doloment** [comment]
А как на счет того, чтобы сделать мумификацию, есль игрок хочет сохранить труп. Инвенторя не будет в нем.

**Comment by Mikola314** [comment]
Doloment, не понял идеи. Если выложить труп для красоты, в него не удастся положить предметы.

**Comment by vladtcvs** [comment]
Может в скелет превращаться?

**Comment by Mikola314** [comment]
vladtcvs , а вот это дельная мысль.

**Comment by vladtcvs** [comment]
Хотя через некоторое время тогда вид вокруг спавна будут удручающ..

**Comment by alek13** [comment]
отклонена
