### ISSUE TITLE
Кольцо воды в слоте брони блокирует отображение брони

### ISSUE THREAD

**Issue by vladtcvs** [lord-server/lord#590]
**Описание ошибки:**

Если кольцо в слоте щита то все ок

![изображение](https://user-images.githubusercontent.com/3390973/164816545-648eca5e-16e0-43e3-a87b-5c5d9aacddbd.png)

Но если поместить в слот кирасы, штанов или шлема, то пропадает из превью и с фигурки

![изображение](https://user-images.githubusercontent.com/3390973/164816589-62abba2b-64e3-477b-9e4e-8c05c7bf563d.png)

**Comment by alek13** [comment]
Исправлено рефакторингом.
