### ISSUE TITLE
"Дырки" от горного посоха при малой высоте

### ISSUE THREAD

**Issue by vladtcvs** [lord-server/lord#607]
![изображение](https://user-images.githubusercontent.com/3390973/170133528-2199e040-f57b-49f0-a9e0-a13cf6ce8288.png)

**Comment by vladtcvs** [comment]
Вероятно это связано с тем, что ставим землю только если нода пустая, а там на самом деле может быть уже трава

**Comment by Doloment** [comment]
Проверку на plantlike делать будешь?
