### ISSUE TITLE
У льда проблемы с текстурами и звуками

### ISSUE THREAD

**Issue by VanicGame** [lord-server/lord#626]
**Описание ошибки:**

У льда и его ступеней разные текстуры и разные звуки. Лёд звучит, как стекло, а ступени имеют свой звук.
![screenshot_20220706_105818](https://user-images.githubusercontent.com/82447582/177499859-b0ccfb9d-048b-4e5a-a45e-71f6a8bd54ed.png)
![screenshot_20220706_105814](https://user-images.githubusercontent.com/82447582/177499864-e874f91d-7c05-4895-90a5-af9f07b69b96.png)

**Как воспроизвести:**

Шаги воспроизведения на *[<сервере|полигоне|локальном окружении|копии мира>]*:
1. Поставить все блоки в ряд
2. Потыкать на них
3. Походить по ним
4. Заметить разность во звуках
5. Текстуры и так видно:)

**Ожидаемое поведение:**

Одни текстуры, одни звуки

**Информация о клиенте:**

 - OS: [<Android|Windows|Linux|...>]
 - Client version: [<5.0|5.1|...>]
 - Device: [<ПК|iPhone6|Android-Телефон|Android-планшет|...]

**Дополнительная нформация:**

**Comment by alek13** [comment]
Info:
идет переопределение в `mods/_lott/lottmapgen/nodes.lua:60`:
```lua
minetest.register_node(":default:ice", {
	description = SL("Ice"),
	drawtype = "glasslike",
	tiles = {"lottmapgen_ice.png"},
	is_ground_content = true,
	use_texture_alpha = "blend",
	paramtype = "light",
	freezemelt = "default:water_source",
	groups = {cracky=3, melts=1},
	sounds = default.node_sound_glass_defaults(),
})

```
