### ISSUE TITLE
/home размазывает игрока об землю

### ISSUE THREAD

**Issue by VanicGame** [lord-server/lord#628]
**Описание ошибки:**

Если падая, прописать /home, то получаешь урон от столкновения с землей (будто скорость не гасится)

**Как воспроизвести:**

Шаги воспроизведения на *[<сервере|полигоне|локальном окружении|копии мира>]*:
1. Прыгаем с высоты
2. Пока летим пишем /home
3. После телепорта наблюдаем урон

**Ожидаемое поведение:**

Спасение от гибели

**Информация о клиенте:**

 - OS: FreeBSD
 - Client version: 5.4.1
 - Device: ПК

**Comment by Doloment** [comment]
Решили на созвоне: не баг, закрываем
