### ISSUE TITLE
Факел на воздухе

### ISSUE THREAD

**Issue by Doloment** [lord-server/lord#64]
Повесить на ствол молодого маллорна факел. Срубить маллорн. Факел летает.

**Comment by Mikola314** [comment]
Физику в minetest не завозят

**Comment by albel4** [comment]
Проверял на яблоне. Если срубить полностью то факел таки падает.

**Comment by vladtcvs** [comment]
еще факелы, стоявшие на сгоревших (от назгулов) нодах, не падали

**Comment by Mikola314** [comment]
vladtcvs у фаерболов алгоритм как у WE (редактора мира). А при таком методе уничтожения нодов не запускается пересчёт.

**Comment by vladtcvs** [comment]
Проблема не только в факелах, но еще и в сыпучих материалах. Причина та же самая, но последствия хуже. Если назгул сделает "подкоп" под песок или гравий, а игрок потом пойдет по песку и как-нибудь с ним провзаимодействует, то провалится вниз
