### ISSUE TITLE
MTGcarts: в логи пишется WARNING

### ISSUE THREAD

**Issue by VanicGame** [lord-server/lord#642]
**Описание ошибки:**

В логах: `2022-07-14 17:05:59: WARNING[Main]: Not registering alias, item with same name is already defined: default:rail -> carts:rail`

**Comment by ssdaniel24** [comment]
```shell
$ grep -r 'default:rail'
lord/legacy/init.lua:minetest.register_alias("default:rail", "carts:rail")
_minetest_game/carts/rails.lua:minetest.register_alias("default:rail", "carts:rail")
$
```

**Comment by Doloment** [comment]
А, ну видимо нужно просто удалить один из alias-ов
