### ISSUE TITLE
Идеи игроков

### ISSUE THREAD

**Issue by Doloment** [lord-server/lord#65]
- [ ] Люстра (XFCE)

- [ ] Дротики (Это и далее от Зама) (P.S.: Блин, это ж сначала надо впендюрить мод Bows...)

- [ ] Цветную глину (Я тоже ее хочу. Пожалуй, и займусь ею)

- [ ] Драконы (Код есть, нужно прорабатывать мелочи)

Позже допишу

**Comment by Mikola314** [comment]
люстры с цепями у нас  и так висят в списке https://github.com/lord-server/lord/issues/52 на прикручивание, но были замечены баги с установкой, будем перепроверять

**Comment by Doloment** [comment]
Я как-раз дописываю)

**Comment by vladtcvs** [comment]
Орлы

**Comment by Mikola314** [comment]
vladtcvs, https://github.com/lord-server/lord/issues/55

**Comment by vladtcvs** [comment]
Согласованность решеток и решетчатых дверей. Сейчас решетка посередине ноды, а дверь с краю.

**Comment by vladtcvs** [comment]
Не туда написал(

**Comment by Doloment** [comment]
Есть идея: пусть драконы будут дропать "Кристалл хризолита в породе", из которого будет изготавливаться Кольцо Зверя, а, возможно, и другой кристалл: Ильванит (ранее фианит), используемый для кольца Гномов. В моей ветке  неограненный кристалл Ильванита получается путем сплавки кварца и Танзанита (ранее сапфир). Можно изменить крафт на 
```"Неограненный Кристалл Хризолита"+"Неограненный Кристалл Танзанита"→(сплавление, возможен шанс неудачи)→"Неограненный Кристалл Ильванита"```
