### ISSUE TITLE
Неизвестный итем из bush_leaves

### ISSUE THREAD

**Issue by VanicGame** [lord-server/lord#650]
**Описание ошибки:**

Неизвестный итем с некоторым шансом выпадает из ноды `default:bush_leaves`.

**Как воспроизвести:**

Шаги воспроизведения на *[<сервере|полигоне|локальном окружении|копии мира>]*:
1. Через /list находим `default:bush_leaves`
2. Выдаем себе стак
3. Устанавливаем и раскапываем до тех пор, пока в нашем инвентаре не появится неизвестный итем

**Дополнительная информация:**

Относится к #563

Этот блок нельзя найти в мире (вроде), поэтому в релиз 22.07 я его не включаю.

**Comment by ssdaniel24** [comment]
```lua
	drop = {
		max_items = 1,
		items = {
			{items = {"default:bush_sapling"}, rarity = 5},
			{items = {"default:bush_leaves"}}
		}
	},
```
Из `mods/_minetest_game/default/nodes.lua`.

**Comment by ssdaniel24** [comment]
```shell
$ grep -r 'default:bush_sapling'
...
lord/_overwrites/MTG/default/init.lua:minetest.unregister_item("default:bush_sapling")
...
```
