### ISSUE TITLE
Косяк с крафтами

### ISSUE THREAD

**Issue by Doloment** [lord-server/lord#66]
Много крафтов, которые, по логике вещей, должны быть бесформенными - форменные.
- [x] Разные двери с замком
- [x] Разные сундуки с замком
- [x] Прилавок
- [x] Тилкал
- [x] Галворн
- [x] Итильдин (открытый)
- [x] Итильдиновый камень (открытый)
- [x] Итильдин (закрытый)
- [x] Итильдиновый камень (закрытый)

**Comment by Mikola314** [comment]
Согласен.

**Comment by Doloment** [comment]
Не все
