### ISSUE TITLE
Невозможность варки зелий

### ISSUE THREAD

**Issue by ssdaniel24** [lord-server/lord#687]
На полигоне обнаружена невозможность приготовить любые виды зелий с любым видом топлива в лаборатории. Процесс варки просто-напросто не начинается, и анимация пузырьков не стартует.

Баг появился уже после последнего релиза, так как на боевом такого не происходит.

![Иллюстрация бага](https://user-images.githubusercontent.com/107036969/181832298-ff23c15f-6e7d-47f5-bdb9-16d1ae704311.png)

**Comment by VanicGame** [comment]
Локально и полигонально всё работает в штатном режиме. Скорее всего @ssdaniel24 пытался сварить зелье в ghost лаборатории, на которой не работает ABM. Вопрос исчерпан, issue закрывается
