### ISSUE TITLE
После прочтения книги палантиров перемещение по-прежнему невозможно

### ISSUE THREAD

**Issue by weqqr** [lord-server/lord#69]
скорее всего, возникло после 546753a31193dfbd019d3c7c610805c54ebbdef3

**Comment by Mikola314** [comment]
Sc, всё работает. Сейчас проверил на свежесозданном игроке.
Чтобы получить привилегию, нужно сначала своими ручками смастерить палантир и только потом своими ручками смастерить книгу.
