### ISSUE TITLE
Убрать предупреждения "No craft recipe known for output"

### ISSUE THREAD

**Issue by ssdaniel24** [lord-server/lord#710]
При запуске игры возникает (пока что) пара предупреждений:
```
2022-08-22 10:48:37: WARNING[Main]: No craft recipe known for output
2022-08-22 10:48:37: WARNING[Main]: No craft recipe known for output
```

[Достоверно известно](https://github.com/minetest/minetest/blob/master/src/script/lua_api/l_craft.cpp#L302), что такие предупреждения печатает функция `minetest.clear_craft`, но определить какой именно вызов функции провоцирует печатать предупреждения представляется возможным только методом проб и ошибок, т.е. пробовать удалять тот или иной вызов функции и смотреть на результат.

**Comment by alek13** [comment]
происходит в `mods/lord/_overwrites/MTG/farming/init.lua` при:
```lua
minetest.clear_craft({output = "farming:hoe_mese"})
```
и
```
minetest.clear_craft({output = "farming:hoe_diamond"})
```
на сколько помню они в самом MTG были выпилены, но что-то осталось для совместимости.
вроде в комметах в самом `mods/_minetest_game/farming` это было описано.
