### ISSUE TITLE
Refactoring: Убрать поддержку `inventory_plus`, `unified_inventory` и `inventory_enhanced`

### ISSUE THREAD

**Issue by ssdaniel24** [lord-server/lord#754]
Эти моды у нас не используется, однако упоминаний его в коде очень много.

**Comment by alek13** [comment]
Скорее всего это в LOTT. Если да, то нужно добавить в описание.
После "обновления" модов: #xxx, #yyy, #zzz. (ссылки на issues с обновленим модов, в которых есть упоминания)

**Comment by alek13** [comment]
https://github.com/lord-server/lord/pull/784/commits/868075260d822da96a45b7be1c065dbd08ef65f1

**Comment by vladtcvs** [comment]
Кстати, в моем обновлении creative, часть этой работы сделана
