### ISSUE TITLE
Добавление нового мода на луки

### ISSUE THREAD

**Issue by Doloment** [lord-server/lord#76]
Добавить мод Minecraft-like bows на сервер с некоторыми изменениями для метания дротиков и ножей (можно добавить под названием lord_throwing) . Превратить этот мод тупо в API. Удалить мод lottthrowing и изменить метание яйца (на данной версии lord-master не кидается, хз поч; в lord-patch-8 кидается) на API этого мода. 

P.S.: ссылка - https://forum.minetest.net/viewtopic.php?f=9&t=18310

**Comment by googolgl** [comment]
Там еще метательные ножи есть. Может и их тоже?

**Comment by vladtcvs** [comment]
Сейчас делаю вариант луков и стрел, унифицированный с методом стрельбы мобов

**Comment by vladtcvs** [comment]
Яйца и прочее туда же перенесу

**Comment by vladtcvs** [comment]
А кстати, будет ли осмысленно сделать разные типы брони, кольчуги там всякие, встойчивые против одних типов оружия, но менее устойчивые против других?

**Comment by Mikola314** [comment]
vladtcvs идея хорошая. 
У нас на рассмотрении ещё есть https://github.com/lord-server/lord/issues/25

**Comment by alek13** [comment]
неактуально, пилим свои
