### ISSUE TITLE
баги в нодах

### ISSUE THREAD

**Issue by vladtcvs** [lord-server/lord#77]
1) решетка и решетчатая дверь не подходят друг другу.

**Comment by Doloment** [comment]
2. При использовании текстурпака не заменяется текстура у тропинки из гравия в инвентаре, хотя на модельке это происходит. Видимо для инвентаря присвоено отдельное изображение.

**Comment by Mikola314** [comment]
Doloment, для некоторых объектов отдельно прописываются текстуры в инвентаре и на модели

**Comment by albel4** [comment]
Doloment, это не баг. Просто в текстур-паке нет изображения для инвентаря. Обычно файл изображения для инвентаря дополняется суффиксом _inv

**Comment by albel4** [comment]
vladtcvs, поясни про решетку и решетчатую дверь. Чем они не подходят?

**Comment by Mikola314** [comment]
albel4, он про то, что решётка располагается посередине нодов в форме "+", "-" или "т", а двери - на располагаются вдоль грани нода. Выглядит, что дверь висит в воздухе. Аналогично со стеклянными стенами. Это не баг, а скорее непродуманный набор объектов для стройки.

**Comment by albel4** [comment]
Поскольку багом не является закрываю проблему.
