### ISSUE TITLE
Исчезновение галворного шлема

### ISSUE THREAD

**Issue by Ingram900** [lord-server/lord#793]
Исчезает галворный шлем.

Надеваю шлем на персонажа. Открываю вкладку снаряжение (инвентарь). Проверяю: шлем галворный надет, на месте, даже зеленой полоски на нем еще нет (то есть изношенности на шлеме нет).

Выхожу из майнтеста (полностью закрываю приложение). Потом захожу. Сразу проверяю инвентарь (снаряжение). Шлема галворного уже нет. Хотя какое-то время на голове перса он еще отображается. Но можно уже надевать например железный шлем. При этом шлема галворного нигде нет.

file:///home/slava3/Рабочий стол/галворн шлем/Screenshot_1_шлем есть.jpg
file:///home/slava3/Рабочий стол/галворн шлем/Screenshot_2_шлем на персе виден_ВЫХОЖУ из игры.jpg
file:///home/slava3/Рабочий стол/галворн шлем/Screenshot_3_ЗАШЕЛ в игру_шлем виден еще.jpg
file:///home/slava3/Рабочий стол/галворн шлем/Screenshot_4_А тут шлема уже нет.jpg
file:///home/slava3/Рабочий стол/галворн шлем/Screenshot_5_можно надевать железный.jpg

У меня установлена Кубунту 20.10 на ноутбуке. 
Майнтест 5.3.0

И вот что еще. У меня ноутбук здорово греется (нужно термопасту менять)

**Comment by VanicGame** [comment]
Не воспроизводится.
Заходил с телефона и мобильного интернета. Зашёл, одел, вышел из игры совсем, зашёл, шлем на месте.

**Comment by Ingram900** [comment]
> Извиняюсь, что не заметил вас в игре. Подчеркиваю: Я С НОУТБУКА захожу. ноутбук и мобильник - не одно и тоже. 
То, что скриншоты не загрузились - это я сам понял.
Попытаюсь дать ссылку на облако. 
[https://cloud.mail.ru/public/41U4/rwn9o8GCX](url)

вот еще
_https://cloud.mail.ru/public/41U4/rwn9o8GCX - на тот случай, если не получилась первая ссылка
 
И ВНИМАТЕЛЬНО читайте названия скриншотов. Там лучше некуда описано суть происходящего. От первого до пятого скриншота. Я уже 3 или 4 шлема потерял таким образом.

**Comment by Ingram900** [comment]
Скопируйте ссылку, не поленитесь и скачайте скриншоты. И по порядку посмотрите что происходит у меня.

**Comment by VanicGame** [comment]
> Подчеркиваю: Я С НОУТБУКА захожу. ноутбук и мобильник - не одно и тоже.
С точки зрения formspec и itemstack разницы нет. Если исчезает предмет на стороне сервера дело явно не в клиенте. Если исчезает предмет на стороне клиента, стоит проверить соединение с интернетом и пинг

**Comment by VanicGame** [comment]
![Uploading a3{6264f59} (50f50ea5-1dce-4297-b52f-d317aff2b145 id=0x7f0a03cc tag=BaseCommentFragment) …]()
Это что угодно, но не галворновый шлем, так что проблема начинается с самого надевания шлема.

**Comment by Ingram900** [comment]
Наверное дело в интеренете. Или в процессе надевания шлема он исчезает.

**Comment by alek13** [comment]
баг не воспроизводится. Ставлю `stale`, если подробностей не будет, то закроется сам через 2 недели
