### ISSUE TITLE
Новая текстурка палантира

### ISSUE THREAD

**Issue by SemiGark** [lord-server/lord#795]
Предлагаю сменить текстуру паланитра в инвентаре на мою
![default_tool_woodaxe](https://user-images.githubusercontent.com/115567900/195144320-82a59e46-4438-4198-b4fd-1440b5865b08.png)

**Comment by VanicGame** [comment]
@SemiGark, раскрой идею и удали шаблон, пожалуйста

**Comment by VanicGame** [comment]
#767
