### ISSUE TITLE
Поворот досок при установке

### ISSUE THREAD

**Issue by weqqr** [lord-server/lord#833]
**Описание ошибки:**

При установке `default:wood` направление взгляда игрока не учитывается, а остальные доски поворачиваются.

**Comment by alek13** [comment]
Думаю тут стоит остальные доски сделать так же, как `default:wood`.
В этом случае на самом деле:
 - удобнее при строительстве (в подавляющем большинстве случаев)
 - меньше кривых построек с разнонаправленными досками
 - если нужно (напр, узор разними направлениями сделать), всегда можно повернут отвёрткой
