### ISSUE TITLE
To `5.7`: мигрировать mod-storage на PostgreSQL

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#845]
- [x] на Полигоне
 - [x] на Боевом (после тестирования на полигоне)

**_примечание:_**

предварительно:
 - в коде нужно проверить нет ли записи напрямую в эту папку (где-то видел такое, если не путаю)
 - на обоих серверах грохнуть остатки от старых модов (от `climate` вроде было)
 
## Зависит от:
 - [x] lord-server/infrastructure#1
 - [x] lord-server/infrastructure#2

**Comment by weqqr** [comment]
PostgreSQL для mod storage появится только в 5.7
