### ISSUE TITLE
To `5.6.1`: Not registering alias, item with same name is already defined: doors:door_steel -> lord_doors:door_steel

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#852]

**Comment by Doloment** [comment]
Проблема в том, что перед регистрацией alias дверь не была unregistered, хотя в коде эта строчка была. Что происходило: загружался сначала мод с алиасом, а только потом мод, в котором un-регистрировалась дверь.

Решение — добавить последний мод в зависимости к первому.

В общем, всплыло то, о чем я говорил в #598
