### ISSUE TITLE
краш сервера

### ISSUE THREAD

**Issue by SemiGark** [lord-server/lord#877]
unknowitem крашит сервер 

если попробовать поставить unknowitem в рамку/пьедестал то сервер выдает ошибку

(сказали, что лучше не стоит показывать как воспроизводить:D) 

берем unknowitem, и ставим в рамку/пьедестал

сервер выходит из строя на минуты 2-3

ожидал что выскочит ЦП

**Информация о клиенте:5.5.0**

 - OS: [Windows]
 - Client version: [5.5.0]
 - Device: [ПК]

**Comment by Doloment** [comment]
Дубликат #799, Исправлено. #876
