### ISSUE TITLE
Саженцы эвкалипта не выпадают при опадении листвы

### ISSUE THREAD

**Issue by pilsnerivk** [lord-server/lord#894]
**Описание ошибки:**

При срубке дерева активируется опадение листвы, в результате которого не выпадают саженцы эвкалипта. При этом при ручном ломании листвы дроп работает нормально.
Стоит проверить с другими деревьями.

 - OS: Windows
 - Client version: 5.3.0
 - Device: ПК

**Comment by Doloment** [comment]
Оказалось связано с `default:junglesapling`, надо решать что с ним делать
