### ISSUE TITLE
Бесконечный яблоневый забор и защищенная табличка

### ISSUE THREAD

**Issue by pilsnerivk** [lord-server/lord#903]
**Описание ошибки:**
Бесконечный яблоневый забор и защищенная табличка
Проверьте также другие заборы и таблички)))

**Как воспроизвести:**

Шаги воспроизведения на *[<сервере|полигоне|локальном окружении|копии мира>]*:
1. Открываем инвентарь
2. Берём 'яблоневый забор', защищенная табличка
3. Устанавливаем на '....'
4. В инвентаре остается тоже количество, при сборе установленный прибавляется

**Информация о клиенте:**

 - OS: Windows
 - Client version: 5.6.1
 - Device: ПК

**Comment by Doloment** [comment]
Из заборов работает только на яблоневом, а вот таблички, видимо, все подвержены багу
