### ISSUE TITLE
Нельзя приручить пони

### ISSUE THREAD

**Issue by Petus228666** [lord-server/lord#915]
**Описание ошибки: нельзя приручить пони**

**Как воспроизвести: попытаться приручить пони снопом ячменя**

Шаги воспроизведения на сервере:

1. Берём сноп пшеницы 
2. Кормим пони (ПКМ)
3. Видим, что пони не приручается
(сноп в руке не убавляется)

**Информация о клиенте:**

 - OS: [<Windows 11>]
 - Client version: [<5.5.1>]
 - Device: [<ПК>]

edit: Van

**Comment by VanicGame** [comment]
https://github.com/lord-server/lord/blob/178eec5d72f14f546d1f1674c19073940b14ba48/mods/lord/lottmobs/horse.lua#L780 — приручается снопом ячменя

**Comment by VanicGame** [comment]
Автор сказал, что не получилось ячменем. Надо проверить и исправить

**Comment by VanicGame** [comment]
https://github.com/lord-server/lord/blob/dev/mods/_lott/lottfarming/barley.lua#L67 — У нас lottfarming, а в определении пони указан farming. Надо изменить

**Comment by Petus228666** [comment]
Такая же проблема с лошадьми
пробовалось:сноп пшеницы,сено
