### ISSUE TITLE
Износ брони происходит только при уроне

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#977]
**Описание ошибки:**

Если броня "выдержала" и урона не было, износ брони не засчитывается, несмотря на то, что по игроку били.

**Дополнительная информация:**

Т.к. обработка происходит только при изменении hp: https://github.com/lord-server/lord/blob/882eb4d0a3d5969cc9fd097cdd3c124b07fd8761/mods/lord/lottarmor/armor.lua#L305

посмотреть `minetest.register_on_punchplayer()`

**Comment by vladtcvs** [comment]
Задача требует дополнительного изучения. Например, если тебя атакует кот, то он не должен при этом повреждать доспехи

**Comment by alek13** [comment]
Ориентироваться на то, какой урон должен нанестись. Если маленький, то значит и самой броне не нанесено "урона" (износа)

**Comment by vladtcvs** [comment]
А должна ли броня постепенно изнашиваться если просто ходить в ней?

**Comment by alek13** [comment]
нет, не стоит. Только если сапоги, но они вроде и так изнашиваются

**Comment by vladtcvs** [comment]
Кстати, в тему сапогов. У нас есть сапоги броня и ботинки одежда. Ботинки под сапогами выглядит странно
