### ISSUE TITLE
новая текстура жемчуга

### ISSUE THREAD

**Issue by Petus228666** [lord-server/lord#979]
Предлагаю сменить текстуру жемчуга на эту из Lord of the test
![lottores_pearl](https://user-images.githubusercontent.com/122599616/216472301-fa5c3167-3cef-4702-a017-d21295cdbb51.png)

**Comment by VanicGame** [comment]
![Screenshot_2023-02-03-07-23-48-01_572064f74bd5f9fa804b05334aa4f912.jpg](https://user-images.githubusercontent.com/82447582/216512107-d91addea-3083-4fab-91c8-a9c05510ee2d.jpg)

**Comment by Petus228666** [comment]
а это не переделанная текстура палантира из #767?

**Comment by VanicGame** [comment]
> а это не переделанная текстура палантира из #767?

Это палантир переделанная текстура жемчуга

**Comment by Doloment** [comment]
Таим макаром уж и блок переделай @VanicGame

**Comment by Petus228666** [comment]
@Doloment  а смысл если он прозрачный?

**Comment by VanicGame** [comment]
> Таким макаром уж и блок переделай @VanicGame 

Алек сказал, интерпретирую, «Он используется во многих постройках, поэтому только если не будет сильно отличаться»

**Comment by VanicGame** [comment]
> > Таким макаром уж и блок переделай @VanicGame 
> 
> Алек сказал, интерпретирую, «Он используется во многих постройках, поэтому только если не будет сильно отличаться»

Плюс, у него текстура с текстурой соли завязана, вроде как. Или просто копия... Я не помню, в общем, скажи ещё, что и соль надо переделать)

**Comment by Doloment** [comment]
Соль-то не особенно, а вот жемчуг надо. А то у него в принципе текстуры не видно из-за прозрачности. Надо делать прозрачным не блок, а текстуру

**Comment by VanicGame** [comment]
> Соль-то не особенно, а вот жемчуг надо. А то у него в принципе текстуры не видно из-за прозрачности. Надо делать прозрачным не блок, а текстуру

Я ему делал 80% прозрачности, поэтому текстура у него на 20% прозрачна. А сама текстура, текстура соли... Там ещё где-то был песчаник наложен, я не помню
