### ISSUE TITLE
Каменные блоки: производные мордорского камня и кирпича

### ISSUE THREAD

**Issue by alek13** [lord-server/lord#999]
- булыжник
 - чёрные кирпичи
 - чёрные сглаженнные блоки
 - красные сглаженные блоки
 - ступени/плиты для них всех
 - (чёрные/красные ограды, если их не сделали с задачей оград)

**Comment by Doloment** [comment]
Для #995 также добавлены булыжник, гравий и песок

![Image](https://user-images.githubusercontent.com/22934348/222869930-4a2f1465-adb7-443c-b005-22f991da201a.png)
